### ISSUE TITLE
Sudden transcoding between PMS and PMP 2.24 on same HTPC computer

### ISSUE THREAD

**Issue by Pottypotsworth** [plexinc/plex-media-player#812] opened 2018-12-18 15:23 UTC
Seemingly playing video files with a bitrate higher than 3,000 from PMS and PMP 2.24 on the same computer will result in PMS transcoding as follows...

Video: Transcoding H264 (HW) to H264 (hw)
Audio Transcoding TrueHD to OPUS

--

PMS Version: 1.14.1.5488
PMP Version: 2.24.0.924-63fcaa8e
Platform (Windows/OSX/Embedded): Windows 10

### Steps to reproduce
Open PMP, play a high bitrate video file.

### Current behavior
The video will be transcoded. Audio will be stripped right down to OPUS.

### Expected behavior
Video should direct play as per the way it always has. Reverting back to PMP 2.22 fixes the issue.

PMS Log: https://discourse-cdn-sjc1.com/plex/uploads/default/original/3X/8/4/84b8373878b3659c37eb081a286ddfb0f42fb1a7.log

PMP Log: [PlexMediaPlayer.log](https://github.com/plexinc/plex-media-player/files/2691104/PlexMediaPlayer.log)

A little more info can be found at - https://forums.plex.tv/t/sudden-transcoding-between-pms-and-pmp-on-same-htpc-computer/348056

**Comment by OttoKerner** [comment] 2018-12-20 14:20
@Pottypotsworth 
- your value in 'LAN Networks' is currently ignored. remove the space character after the comma (although I think the localhost network can be omitted anyway)
- in 'List of IP adresses...' you better fill up the LAN address to `192.168.0.0/24` (you are currently missing the last octet)

Then close and re-open your plex server and re-evaluate.

**Comment by Pottypotsworth** [comment] 2018-12-20 14:23
Hi @OttoKerner  

Something is happening with the current value in "Lan Networks" because that FIXES the issue I outlined above. If I leave the lan networks value blank as it has been for the past 8 years then the transcoding issue starts up again.

**Comment by Pottypotsworth** [comment] 2018-12-20 14:42
![screenshot 2018-12-20 at 22 41 39](https://user-images.githubusercontent.com/20905543/50291076-75453f00-04a8-11e9-9e23-f6f9fc47f8b7.png)

I changed the inputs as you suggested, @OttoKerner, this causes the transcoding issue to start again :(

**Comment by Pottypotsworth** [comment] 2018-12-20 14:49
![screenshot 2018-12-20 at 22 41 39](https://user-images.githubusercontent.com/20905543/50291413-7f1b7200-04a9-11e9-9cac-6be002bff8aa.png)

Last screenshot didn't work.

**Comment by OttoKerner** [comment] 2018-12-20 17:04
Whoa. Are you sure your server is actually using the 192.168.0.0 network?
OK, then add the 127.0.0.0/8 after a comma (without space) into LAN Networks again,

**Comment by Pottypotsworth** [comment] 2018-12-20 17:24
![image](https://user-images.githubusercontent.com/20905543/50300194-a3ce1480-04be-11e9-94ee-8934b72ce8ca.png)

Thanks for the continued help, @OttoKerner  - Yep I am absolutely sure that everything is on the 192.168.0.X network. The PC running PMS and PMP is on 192.1689.0.150

Your changes didn't work, and now when i change back to the settings I had in my second message above, they don't fix the issue. Everything is being transcoded. The only fix is to go back to PMP 2.22.

I can't stress enough that i have no other network issues. Both Apple TVs can direct play from the server, computers can see each other fine, transcoding just hasn't existed for me at all until PMP on the same computer as PMS was updated to 2.4. What on earth could have changed to cause this? Why would I even need to mess around with network settings when PMS and PMP are on the very same computer?

Assuming you understand the PMP logs better that I, is there something in there that indicates why this is happening?

Thanks

**Comment by Pottypotsworth** [comment] 2018-12-20 17:32
Unselecting IPv6 Support seems to have fixed the issue, @OttoKerner - I am 100% sure that it has always been ticked in the past though.

**Comment by Pottypotsworth** [comment] 2018-12-20 17:38
![image](https://user-images.githubusercontent.com/20905543/50300979-00323380-04c1-11e9-9170-694a19a84b44.png)

^ Current working network settings on 2.24

**Comment by mseeley** [comment] 2018-12-21 03:17
Yeah, very odd. You're logs indicate that direct play is prevented due to bitrate:

```
2018-12-18 23:17:13 [ INFO  ] JS: [MDE] Analyzing direct play 
2018-12-18 23:17:13 [ INFO  ] JS: [MDE] Invalid profile property; bitrate: 39204 > 3000 
2018-12-18 23:17:13 [ INFO  ] JS: [MDE] Cannot direct play: validateProfileProperty:maxBitrate 
2018-12-18 23:17:13 [ INFO  ] JS: [Player] Can direct stream? true (isAllowed: true) 
2018-12-18 23:17:13 [ INFO  ] JS: [MDE] Analyzing video direct stream 
2018-12-18 23:17:13 [ INFO  ] JS: [MDE] Invalid profile property; bitrate: 39204 > 3000 
2018-12-18 23:17:13 [ INFO  ] JS: [MDE] Analyzing audio direct stream 
2018-12-18 23:17:13 [ INFO  ] JS: [MDE] Analyzing playability 
2018-12-18 23:17:13 [ INFO  ] JS: [MDE] Finished analysis of 1080 (mkv, h264, truehd, 41, high) 
2018-12-18 23:17:13 [ INFO  ] JS: canPlay: true 
2018-12-18 23:17:13 [ INFO  ] JS: canDirectPlay: false 
```

I don't know what could have caused this and we've been unable to reproduce. I also couldn't reproduce the issue when enabling IPV6 support. This last test could be invalid as I'm unsure if my local network talks IPv6.

@OttoKerner, @Pottypotsworth please close this issue after you finish discussions. I don't doubt that something odd was happening. Although without a clean repro or wider spread error reports we're not going to prioritize a bug hunt.

**Comment by Pottypotsworth** [comment] 2018-12-21 07:13
That's fair enough @mseeley, i'll give it the weekend for any other responses (and to do more testing where I can) and then close this out after that.

**Comment by OttoKerner** [comment] 2018-12-21 09:07
I'd also re-evaluate after setting 'Preferred network interface' back to 'Any'

**Comment by mseeley** [comment] 2019-01-15 20:54
Thanks for working through this fellas.

**Closed by mseeley** 2019-01-15 20:54 UTC
