### ISSUE TITLE
No "Exit" option in UI - only "Relaunch" and "Cancel" [Ubuntu 16.10 & SteamOS/Debian 8]

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-media-player#354] opened 2016-06-06 18:33 UTC
<strike>Not sure how wide this issue may be so I included Debian 8 as a reference.</strike> Issue effects Ubuntu/Kubuntu 16.04 & 16.10 as well.

When attempting to close the app, I am only met with two options: "Relaunch" and "Cancel"

Further, "Relaunch" doesn't actually ever relaunch the application.

**To be clear, there is an "Exit" option in the top right menu but the popup dialog where you actually make your choice has no such option.**

**Comment by wm4** [comment] 2016-06-06 18:35
"Relaunch" exits here (Debian too). Is the button just labeled incorrectly?

**Comment by Enigma0** [comment] 2016-06-06 18:37
Could be. In the case with SteamOS/BPM, the UI hangs after selecting "Relaunch" so it's not entirely clear if it really ends or if the process hangs for a bit.

**Comment by mdesdin** [comment] 2016-07-22 18:02
For a temporal fix: edit pmp conf file and find the option showPowerOptions inside the main group and set it to false. And you get your exit back.

**Comment by Enigma0** [comment] 2016-07-26 19:32
Where is that .conf file?

**Comment by mdesdin** [comment] 2016-07-27 11:09
Here explained: [https://support.plex.tv/hc/en-us/articles/207338798-Advanced-Configuration](url)

**Comment by Enigma0** [comment] 2016-07-27 21:02
Thanks I'll look into that. FYI the github link does some redirect to a 404 page (https://github.com/plexinc/plex-media-player/issues/url). Copying and pasting works fine though.

**Comment by mdesdin** [comment] 2016-07-27 21:09
yes, thanks for pointing out, my bad, it is fixed now.

**Comment by Enigma0** [comment] 2016-08-12 13:49
That fixed it locally. I'll leave this open so it gets fixed globally.

**Comment by ProfessorKaos64** [comment] 2016-08-22 11:10
If we are packaging PMP, can we set this in the conf file ahead of time, or is is more safe to have it auto generated?

**Comment by Enigma0** [comment] 2016-12-09 05:49
This is still an issue. How is it figuring out what options to show? Maybe I don't have some utility installed?

**Comment by Enigma0** [comment] 2018-04-11 12:29
Still a problem yes

**Comment by LongChair** [comment] 2018-04-11 12:39
@markus101 : Could you tell me if this is known ?

**Comment by LongChair** [comment] 2018-04-11 17:51
@Enigma0 : i think the issue is coming from your linux build. PMP assumes linux build is embedded. Embedded has pmp startup with systemd which results in restarting when exiting.
When building on a regular linux distro it will report that it can relaunch.

I will look into having that capability changed checking for embedded rather than linux.

**Comment by Enigma0** [comment] 2018-04-11 18:04
Sounds about right - that resolution would be appreciated.

Also, relaunch doesn't actually work anyway. If it did, that would be useful.

**Comment by LongChair** [comment] 2018-04-11 18:13
Relauch would quit i suppose.

Making it work would need an external program that relaunch it like systemd.
That probably won’t happen anytime soon :)

**Comment by Enigma0** [comment] 2018-04-11 18:45
Sure - still it would be nice & probably not too hard.

A script would probably suffice to check if it's still running, if not just launch again.

**Comment by LongChair** [comment] 2018-04-16 05:57
@Enigma0 : i believe that the proper way we can get this fixed for now is to avoid having relaunch and have exit buttons that woukd actually exit.
I could provide a patch for this to try it first and if that works, we could merge it.
Hoz does thqt sound ?

**Comment by Enigma0** [comment] 2018-04-16 14:30
Sure

**Comment by Enigma0** [comment] 2018-04-17 03:03
@LongChair It works!

**Closed** 2018-04-18 18:01 UTC
Labels: component:host, stat:need-feedback, type:bug
