### ISSUE TITLE
flinging from app.plex.tv to PMP results in Playback Error

### ISSUE THREAD

**Issue by dan-the-man-nz** [plexinc/plex-media-player#821] opened 2018-12-21 03:00 UTC
### Test environment
**PMS Version:**  Version 1.14.1.5488 
**PMP Version:**  2.24.0.924-63fcaa8e build date: 2018-12-11
**Platform (Windows/OSX/Embedded):**  Windows 10

### Steps to reproduce
1.  in plex web  (https://app.plex.tv/desktop), select Plex Media Player
![image](https://user-images.githubusercontent.com/906806/50322273-3e6b3980-0539-11e9-9820-c26ec0e6adcd.png)
2. in plex web,   find a video, play it

### Current behavior

1.  PMP does not play the video and instead displays "Playback Error"

![image](https://user-images.githubusercontent.com/906806/50322302-5cd13500-0539-11e9-9b5f-cb80825ef4fd.png)

### Expected behavior

1.  the video should start playing on PMP

[PlexMediaPlayer.log](https://github.com/plexinc/plex-media-player/files/2701348/PlexMediaPlayer.log)

[Plex Media Server Logs_2018-12-21_16-12-29.zip](https://github.com/plexinc/plex-media-player/files/2701373/Plex.Media.Server.Logs_2018-12-21_16-12-29.zip)

**Comment by mseeley** [comment] 2018-12-21 03:21
Odd, I see only this error in the `PlexMediaPlayer.log`:

```
2018-12-21 15:50:25 [ INFO  ] CodecsComponent.cpp @ 567 - "Updating some codecs: msmpeg4v3_decoder" 
2018-12-21 15:50:25 [ ERROR ] CodecsComponent.cpp @ 654 - Codec "msmpeg4v3" exists on disk as "C:/Users/danie/AppData/Local/PlexMediaPlayer/Codecs/97a6171-pmp-260-windows-x86_64/msmpeg4v3_decoder.dll" but is not known as installed - broken codec? 
2018-12-21 15:50:25 [ INFO  ] CodecsComponent.cpp @ 572 - Codec update finished. 
2018-12-21 15:50:25 [ INFO  ] PlayerComponent.cpp @ 225 - Present codecs: h264 hevc vc1 mpeg1video mpeg2video mpeg4 aac aac_latm dca mp3 ac3 png apng mjpeg thp gif vp9 dirac ffv1 ffvhuff huffyuv rawvideo ayuv r210 v210 v210x v308 v408 v410 y41p yuv4 ansi alac flac vorbis opus pcm_f32be pcm_f32le pcm_f64be pcm_f64le pcm_lxf pcm_s16be pcm_s16be_planar pcm_s16le pcm_s16le_planar pcm_s24be pcm_s24le pcm_s24le_planar pcm_s32be pcm_s32le pcm_s32le_planar pcm_s8 pcm_s8_planar pcm_u16be pcm_u16le pcm_u24be pcm_u24le pcm_u32be pcm_u32le pcm_u8 pcm_alaw pcm_mulaw bmp vp6f adpcm_ima_wav mp2 ac3(enc) aac(enc) 012v h264_cuvid hevc_cuvid mjpeg_cuvid mpeg1_cuvid mpeg2_cuvid mpeg4_cuvid vc1_cuvid vp8_cuvid vp9_cuvid msmpeg4 aac_mf eac3_mf eac3_eae truehd_eae mlp_eae eac3_eae(enc) 
```

**Comment by dan-the-man-nz** [comment] 2018-12-21 03:32
additional logs with PMP desktop mode debug enabled
[PlexMediaPlayer.log](https://github.com/plexinc/plex-media-player/files/2701410/PlexMediaPlayer.log)

**Comment by dan-the-man-nz** [comment] 2018-12-21 03:35
console from the kitchen htpc running PMP i was trying to cast to from plexweb..

![image](https://user-images.githubusercontent.com/906806/50323417-6f01a200-053e-11e9-82d0-a308c200149f.png)

**Comment by mseeley** [comment] 2018-12-21 03:39
Thanks Daniel. I wonder if the error is caused by these guys:

```
2018-12-21 16:29:43 [ ERROR ] PlayerComponent.cpp @ 599 - cplayer: Error parsing option cache-pause-initial (option not found) 
2018-12-21 16:29:43 [ ERROR ] PlayerComponent.cpp @ 599 - cplayer: C:/Users/danie/AppData/Local/PlexMediaPlayer/mpv.conf:1: setting option cache-pause-initial='yes' failed. 
2018-12-21 16:29:43 [ ERROR ] PlayerComponent.cpp @ 599 - cplayer: Error parsing option cache-pause-wait (option not found) 
2018-12-21 16:29:43 [ ERROR ] PlayerComponent.cpp @ 599 - cplayer: C:/Users/danie/AppData/Local/PlexMediaPlayer/mpv.conf:2: setting option cache-pause-wait='5' failed. 
```

Hopefully not. It's interesting. I don't see any of the typical UI playback logs in there. I do see these:

```
2018-12-21 16:31:03 [ DEBUG ] RemoteComponent.cpp @ 452 - New poll subscriber: "df6loloi2q3jbfjwb3sv2gfx" "chrome" 
2018-12-21 16:31:03 [ DEBUG ] RemoteComponent.cpp @ 474 - First subscriber added, subscribing to web 
2018-12-21 16:31:03 [ INFO  ] JS: %c[Companion] Successfully processed command from path "/player/timeline/subscribe" 
2018-12-21 16:31:03 [ WARN  ] RemoteComponent.cpp @ 384 - Could not find responseId: 0  - maybe it was removed because of a timeout? 
```

That failed providers request also looks really curious. See how the connections to Dans HTPC is being rejected (status 0). If the content that we're trying to play is from that server than we'd definitely fail immediately.

**Comment by dan-the-man-nz** [comment] 2018-12-21 04:08
those connections that are status 0 you mention, they are all trying to call 127.0.0.1

PMP is not on the same machine as PMS.   i dont know why its trying 127.0.0.1 its never going to work.

JS: %c[Connections] Dans HTPC is unavailable at http://127.0.0.1:32400/media/providers (Status 0) 

https://192-168-1-111.a500b933950541c09d93f24faf04b90d.plex.direct:32400 is fine...

**Comment by dan-the-man-nz** [comment] 2019-03-12 19:11
Coming up 4 months now since this was broken... still broken in latest versions of PMP and PMS

**Comment by mseeley** [comment] 2019-03-12 20:41
We believe this is resolve. @markus101 to verify.

**Comment by markus101** [comment] 2019-03-12 21:15
I landed a fix for this today, it only affected casting to PMP running on Windows in production which made it much harder to pin down, it should be in the next release.

**Closed by markus101** 2019-03-12 21:15 UTC
Labels: next:companion, platform:windows
