### ISSUE TITLE
macOS - Window not focussed after opening PMP in full-screen mode

### ISSUE THREAD

**Issue by generator85** [plexinc/plex-media-player#688] opened 2018-04-15 16:10 UTC
### Test environment
**PMS Version:** 1.12.3.4973
**PMP Version:** 2.8.0.813-6e77dc0c
**Platform (Windows/OSX/Embedded):** MacOS 10.13.4

### Steps to reproduce
1. Open the app in full-screen mode
2. The app doesn't have focus. You'll have to click the window to be able to control it with remote or keyboard.

**Comment by LongChair** [comment] 2018-04-15 16:38
I have just tested this, and i don't seem to have the issue on OSX.
Starting PMP in fullscreen & using keyboard seems to work without any issue.

Could you check what has the focus when you start it ?

**Comment by baz1860** [comment] 2018-04-15 17:35
So, I have this issue too, but it only manifests when another app other than Finder has focus when I invoke PMP, and only when I invoke it from Spotlight.

**Comment by generator85** [comment] 2018-04-15 17:40
I've tested it with a script that shows what app has focus. When starting PMP it gains focus for a sec, after which focus is quickly returned to whatever app had focus before (e.g. Finder, Terminal). 

How I start PMP (like baz1860 describes) doesn't seem to matter in my case.

**Comment by LongChair** [comment] 2018-04-15 18:07
I just grabbed the 2.8.0 from plex.tv and started that one and still can't repro such issue.
My iMac is not quite up to date (10.12.6), but still .

Wether i start PMP from finder or spotlight doesn't seem to have any incidence.

Will update just in case some recent update broke it ...

**Comment by LongChair** [comment] 2018-04-20 04:52
Ok i have been able to reproduce this upgrading to High sierra.
It seems something with high sierra is breaking the Fullscreen mode on startup for a Qt application.
I was able to reproduce this in a Qt sample. Opening a Qt ticket here : https://bugreports.qt.io/browse/QTBUG-67840

**Comment by torarnv** [comment] 2018-04-26 13:47
This fix for this will be in 5.9.x, are you still on 5.7?

**Comment by LongChair** [comment] 2018-04-26 14:25
no we're using 5.9 :)

**Comment by torarnv** [comment] 2018-04-26 14:25
Ah, good! :) The deps in `README.md` could use an update then :)

**Comment by LongChair** [comment] 2018-04-26 14:27
indeed :)

**Comment by torarnv** [comment] 2018-04-26 14:28
You can cherry-pick https://codereview.qt-project.org/#/c/227619/ to very that the fix works for Plex

**Comment by LongChair** [comment] 2018-04-26 14:37
@torarnv thanks, i will try this. 
Meanwhile you're here though i'd have a question.
We have been having historically a lot of issues in out app with QQuickWindow and Fullscreen.

A lot of users reported that it didn't behave like OSX fullscreen in other apps.
One of them came up with this PR that seems to use OSX fullscreen API : https://github.com/plexinc/plex-media-player/pull/706

Could you please confirm that Qt should use native OSX API in the same way ?

I have been testing that PR in our app and it looks to behave good, although I would ofc prefer an upstream fix that can help us reduce code complexity between platforms :)

pinging @briankendall here who authored that PR :)

**Comment by torarnv** [comment] 2018-04-26 14:41
I suspect @briankendall investigated using Qt < 5.9. As of `ef32f16fc284e5017da6016f72a17957fa2fef34` we use `[NSWindow toggleFullScreen:]`, like #706 does, so I would advice against applying #706, and instead updating the build requirements to 5.9 so that all users are using the most up to date code.

**Comment by briankendall** [comment] 2018-04-26 15:10
Honestly I'm not sure which version of Qt I built against -- it would've been whatever the PMP build scripts use by default. @LongChair can you comment on that? I have something like twelve Qt versions installed right now 😆, some compiled myself and most via Qt's official installation tool.

If updating to 5.9 switches QWindow's behavior to use native full screen in macOS, that will certainly help things a lot! However I imagine there will still be a little more work to do since transitioning to and from full screen mode takes times due to macOS's animations, unlike on Windows and Linux where it's basically instantaneous.

**Comment by LongChair** [comment] 2018-04-26 15:15
The current builds we are providing are based on 5.9.0.

I will try to make a build with 5.9.5 that includes this patch and link it to you.
That way you can let us know if it behaves like you would expect on OSX :)

**Comment by torarnv** [comment] 2018-04-26 16:12
@briankendall Sounds like you have quite the setup, yes 😆  

As of https://github.com/qt/qtbase/commit/ef32f16fc284e5017da6016f72a17957fa2fef34, which was in 5.9.0 and up, we use `[NSWindow toggleFullScreen:]`, and never fake fullscreen mode like we did before.

Note that due to the asynchronous nature of the fullscreen transition (due to the animation), the confirmation that the window has been moved into the fullscreen state is when you receive the `QEvent::WindowStateChange` *event*. So you cannot call `setWindowState(Qt::WindowFullScreen)` and immediately after assume the window has moved into the new state, nor can you connect to the `windowStateChanged` signal and assume the same, as that's emitted at the time of the `setWindowState()` call when the `windowState` property of the window changes its value.

All the QWindow and related windowing system APIs are really *requests*, so `setFoo(123)` is really `requestFoo(123)` and the ack from the window system is the final `QEvent::Foo` event.

**Comment by LongChair** [comment] 2018-04-27 05:03
Ok i made a build with the patched Qt 5.9.5 and i have mitigated results :)

 - PMP will now seem to maximize properly on startup.
 - Stopping using this : https://github.com/plexinc/plex-media-player/blob/master/src/utils/osx/OSXUtils.mm#L24-L28 allows to still get the topbar available and play with the toggle fullscreen button.

The main issue I am seeing at this point is that we don't have any input from keyboard available now.
I get a "boing" style noise anytime i try to type in a key, wether I am in fullscreen mode or windowed mode.

Nothing else changed than bumping Qt with that patch in there.

I will link the OSX PMP build here that was built from this : https://www.dropbox.com/s/sb05tzq9lknisi8/PlexMediaPlayer-2.10.0.841-f918ff7d-macosx-x86_64.zip?dl=0

**Comment by torarnv** [comment] 2018-04-27 09:26
> Stopping using this : https://github.com/plexinc/plex-media-player/blob/master/src/utils/osx/OSXUtils.mm#L24-L28 allows to still get the topbar available and play with the toggle fullscreen button.

Not sure what you mean by this 😃 Are you saying with 5.9.5 + the patch you don't need to call `OSXUtils::SetPresentationOptions`anymore, and things work as expected?

> The main issue I am seeing at this point is that we don't have any input from keyboard available now.

I see that here too when running the build you provided. The quit and escape shortcuts seem to work fine though.

I don't think it's related to the patch, but you can try building against an unpatched 5.9.5 just to be sure. I can't reproduce using a simple Qt Quick example, so I'm guessing it's something PMS related? You can try building against 5.9.1/2/3/4 etc to see if it's a regression in Qt, if so please report a bug (with a reduced testcase) and I'll have a look!

**Comment by LongChair** [comment] 2018-04-27 09:30
> Not sure what you mean by this 😃 Are you saying with 5.9.5 + the patch you don't need to call OSXUtils::SetPresentationOptionsanymore, and things work as expected?

Not really, it just makes the menu bar behave funky (avoids it to show when hovering top of window with the mouse, but maybe that's expected). I'll most likely remove this.

> I don't think it's related to the patch, but you can try building against an unpatched 5.9.5 just to be sure. I can't reproduce using a simple Qt Quick example, so I'm guessing it's something PMS related? You can try building against 5.9.1/2/3/4 etc to see if it's a regression in Qt, if so please report a bug (with a reduced testcase) and I'll have a look!

Yeah i'll try to dig that one a bit more, seemed to behave right in 5.9.3 though. So at this point might be looking like a regression from 5.9.3 :)

**Comment by torarnv** [comment] 2018-04-27 09:52
> Not really, it just makes the menu bar behave funky (avoids it to show when hovering top of window with the mouse, but maybe that's expected). I'll most likely remove this.

Yeah, having the menu bar show on hover in fullscreen mode is the default macOS behavior.

> Yeah i'll try to dig that one a bit more, seemed to behave right in 5.9.3 though. So at this point might be looking like a regression from 5.9.3 :)

If that's the case then please report a bug with a reduced testcase (a simple Qt Quick app eg, no web engine dependencies needed), I'd be curious to see what's going on.

**Comment by torarnv** [comment] 2018-04-27 13:57
I've built a version of 5.9.5 with the latest patch applied, you can try it by replacing libqcocoa.dylib in `Plex Media Player.app/Contents/PlugIns/platforms` with the attached file. With the latest patch I don't see the issue of the keyboard producing "beeps".

[libqcocoa.dylib.zip](https://github.com/plexinc/plex-media-player/files/1955372/libqcocoa.dylib.zip)

**Comment by torarnv** [comment] 2018-04-27 14:00
There is a delay of black before you show the Plex logo. I'm assuming this is because it's shown as web content, so it takes a bit of time to bring it up in the web engine. I'd recommend showing a placeholder logo as just a simple QML image item while you are loading the web content.

**Comment by LongChair** [comment] 2018-04-27 14:06
@torarnv : so did you fix anything for that beep thing or is it the patch you added ?
Thanks for the recommendation, will look at this. @markus101 : could that be Ok for you ?

**Comment by LongChair** [comment] 2018-04-27 14:29
I built it from the source tarball that is here http://download.qt.io/official_releases/qt/5.9/5.9.5/single/qt-everywhere-opensource-src-5.9.5.tar.xz

We do have just a few patches applied to it. I don't have the details for all of them in that file due to our dependency builder not allowing regular patches.

[qt5-5.9.5.txt](https://github.com/plexinc/plex-media-player/files/1955478/qt5-5.9.5.txt)

But i don't think those would affect keyboard stuff.

When you say that you don't see the beep issue, that's with the PMP build i linked above ?

**Comment by torarnv** [comment] 2018-04-27 14:52
Yes, I used the same PMP package and just replaced the platform plugin. I’ll continue investigating Monday. 

Are you tracking those patches somewhere? Would make it easier to figure out if they are something that could be fixed upstream if you have a detailed description of why you have them.

**Comment by LongChair** [comment] 2018-04-27 14:55
I can't agree more, i will try to find the history over the weekend. and see what we can do.

**Comment by torarnv** [comment] 2018-04-30 10:47
Here's the patch applied to the `5.9` branch (what will become 5.9.6): https://gist.github.com/torarnv/e27d67ab9593d963e40a7344de960fa4

You can also fetch the `refs/personal/vestbo/mac-fullscreen` ref from the qtbase gerrit repository.

**Comment by torarnv** [comment] 2018-04-30 11:26
If you're building with a recent Xcode, you may need to apply https://codereview.qt-project.org/#/c/225936/ too.

**Comment by torarnv** [comment] 2018-04-30 14:44
Sorry, yeah, that should be `m_nsWindow`, not  `nsWindow`.

**Comment by LongChair** [comment] 2018-04-30 17:51
@torarnv : ok got the Qt build done, and for some reason although the fullscreen behavior looks fine, i still have the issue with not being able to enter any key into the app.

**Comment by torarnv** [comment] 2018-05-02 20:59
So debugging this with @LongChair on IRC it turns out https://github.com/plexinc/plex-media-player/files/1955478/qt5-5.9.5.txt has a hunk applied to a different function than it had in the  https://github.com/plexinc/plex-media-player/blob/master/qt-patches/qt5-5.9.0.patch 

Specifically, from returning `NO` from ` (BOOL)acceptsFirstMouse:(NSEvent *)theEvent` in 5.9.0, the hunk for 5.9.5 returns `NO` from `- (BOOL)becomeFirstResponder`, which tells AppKit that the window doesn't want any keyboard input.

**Comment by LongChair** [comment] 2018-05-03 06:14
@generator85 @baz1860 @briankendall : can you please check if that build fixes the issue ? 

https://www.dropbox.com/s/6154vjdoc4v6ori/PlexMediaPlayer-2.10.0.854-c1633f57-macosx-x86_64.zip?dl=0

**Comment by LongChair** [comment] 2018-05-03 07:13
@torarnv : yeah that bad patch change was the culprit. looks to be working fine now :)

**Comment by generator85** [comment] 2018-05-03 19:05
Seems to work great. Also the app going fullscreen looked a bit messy in the previous version, much better now!

**Comment by LongChair** [comment] 2018-05-07 16:08
PR addressing this issue was merged. Closing :)

**Closed by LongChair** 2018-05-07 16:08 UTC
Labels: component:host
