### ISSUE TITLE
PMP Crashing when seeking

### ISSUE THREAD

**Issue by KrunchMuffin** [plexinc/plex-media-player#201] opened 2016-01-10 02:28 UTC
v1.0.3
Raspberry Pi2

When I play new show and want to skip the intros, I will skip fwd a few times by 30s. sometimes the UI just locks up and I have to restart RPi2. I have attached the log file when it happened and before the restart.

[plexmediaplayer.log.txt](https://github.com/plexinc/plex-media-player/files/83928/plexmediaplayer.log.txt)

**Comment by wm4** [comment] 2016-01-11 11:22
How often can you reproduce it?

**Comment by KrunchMuffin** [comment] 2016-01-11 20:12
Happens quite frequently, but it's random.

**Comment by wm4** [comment] 2016-01-13 19:57
I couldn't reproduce it yet. Will try some more.

**Comment by KrunchMuffin** [comment] 2016-01-13 20:18
Is it possibly memory leak issue? I never turn it off unless forced to and
seems to not happen for a bit after the reboot.

**Comment by wm4** [comment] 2016-01-13 21:38
Interesting angle. I'll try to let it run for a while.

**Comment by KrunchMuffin** [comment] 2016-01-14 23:52
happened again
[plexmediaplayer.log.txt](https://github.com/plexinc/plex-media-player/files/91172/plexmediaplayer.log.txt)

**Comment by wm4** [comment] 2016-01-15 16:06
I've let it running and playing all day. I occasionally seeked back. Except for some mysterious sporadic failures where it showed a "playback did not start in time" error, all seemed well.

Any other circumstances I should be aware of?

(I've been testing with a 1.0.4 development version - I hope it's not just a bug that was fixed since 1.0.3, but I'm not aware of any and it's unlikely.)

**Comment by KrunchMuffin** [comment] 2016-01-15 16:39
I don't think so, other than I usually start clicking as soon as the show starts but after the info bar at the bottom disappears, so not sure if it would be a buffering thing. That's about all I can think of. I will say it was worse in 1.0.2 and got a little better in 1.0.3.

**Comment by OttoKerner** [comment] 2016-01-15 16:51
I happened about some weirdness with seeking myself. 
But it was always a movie with a relatively high bandwidth, so the server showed heavy disk activity when I clicked on 'jump forward' a few times in quick succession.
Apparently, sometimes the server can't deliver the data for the last jump fast enough so a 'time out' is probably triggered.

Part of this problem is the lack of a means to jump further than 30s, so it is almost 'natural' for a user to quickly repeat the 'jump forward' action.

**Comment by KrunchMuffin** [comment] 2016-01-15 21:33
for sure. I am binge watching shameless and I know I have to click 5x to get to the new show. 2:30 mark. Even worse with Homeland, their credits alone are 2:30.

**Comment by KrunchMuffin** [comment] 2016-01-16 02:30
Just happened again. Been watching for about 3hrs. I hit fwd about 5x, than back 3x.

I see this, not sure what it means tho.

> 2016-01-16 02:25:00 [ ERROR ] PlayerComponent.cpp @ 414 - ffmpeg/video: h264_mmal: Did not get output frame from MMAL. 
> 2016-01-16 02:25:00 [ WARN  ] PlayerComponent.cpp @ 412 - vd: Error while decoding frame! 

[plexmediaplayer.log.txt](https://github.com/plexinc/plex-media-player/files/92766/plexmediaplayer.log.txt)

**Comment by wm4** [comment] 2016-01-16 12:50
It means just that what it says: the hardware decoder did not return a frame in time. It waits with a timeout of 100ms. The reasoning is that if fed enough input data, the GPU will usually be much faster than 100ms to return a decoded frame. This could lead to race conditions, but I feel like this is the only way to handle this.

The fundamental problem is that we do not know whether the GPU is busy decoding a frame, or whether the frame was discarded due to a decoding error. Using a timeout is still better than freezing forever. In any case, it should _not_ crash hard, even if playback fails in some way.

It's also possible that this problem is triggered by many seeks in succession (which would reset + resume the decoder, exposing potential problems). But so far I haven't been able to reproduce it even when heavily seeking around. It might be timing related, e.g. related to network speed etc. Hard to tell.

This reminds me: we actually have a crash reporting system. Can you look at the pmphelper.log and tell us which crash dumps it uploaded, if any at all?

**Comment by KrunchMuffin** [comment] 2016-01-16 14:27
Here is that log. not sure if it means one was sent or not.
[pmphelper.log.txt](https://github.com/plexinc/plex-media-player/files/92925/pmphelper.log.txt)

**Comment by KrunchMuffin** [comment] 2016-02-02 20:49
So I have 1.0.4 now and guess what happened the first time I played and tried to seek? Although the UI was still responsive and the little waiting indicator appeared, but I had to press stop and restart the show, then it happened again. frustrating.

**Comment by LongChair** [comment] 2018-04-10 15:54
Supposedly fixed by now.

**Closed by LongChair** 2018-04-10 15:54 UTC
