### ISSUE TITLE
Smart Playlist loading is broken in tv2 branch

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-media-player#607] opened 2017-08-30 02:19 UTC
I just see a "No soup for you!" message.

**Comment by Enigma0** [comment] 2017-09-05 02:51
Bump - this is still broken (can't load/play any of my playlists).

**Comment by mseeley** [comment] 2017-09-05 23:31
Thanks @Enigma0. We'll look into it. 👍

**Comment by mseeley** [comment] 2017-09-05 23:32
@Enigma0, will you please help us with some specifics? I'd really appreciate knowing the related PMS and PMP versions. Thanks!

**Comment by Enigma0** [comment] 2017-09-06 01:28
@mseeley I pulled the tv2 branch and built normally as the main branch is built with mpv on a Ubuntu 17.04 system. Qt 5.9.1.

Latest public PMS & whatever is in latest PMP tv2 branch.

**Comment by mseeley** [comment] 2017-09-06 22:52
Hi @Enigma0, we're not having success recreating any troubles loading playlists. We could use some clean logs for app startup then clicking into the inaccessible playlists.

**Comment by Enigma0** [comment] 2017-09-10 03:56
Really... It's reproducible on all 3 of my systems. @mseeley Where are the logs for this?

**Comment by mseeley** [comment] 2017-09-18 19:25
@Enigma0: https://support.plex.tv/hc/en-us/articles/207338748-Plex-Media-Player-Logs

**Comment by Enigma0** [comment] 2017-09-20 19:38
@mseeley this is everything from the attempt to load the playlist to hitting 'Return' again to 'Try Again' (which fails anyway)

```
2017-09-20 15:19:28 [ DEBUG ] InputComponent.cpp @ 160 - Input received: source: "Keyboard" keycode: "Return" : InputBase::InputkeyState(KeyUp) 
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] Active connection to "?th??" lost authorization 
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] Possible connection error for ?th??, retrying connection tests 
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] Testing all 4 connection(s) for ?th?? 
2017-09-20 15:19:28 [ INFO  ] JS: [Servers] Found all servers = plex.tv, ?th?? 
2017-09-20 15:19:28 [ INFO  ] JS: [Commands] Executing testServerConnection 
2017-09-20 15:19:28 [ INFO  ] JS: [Commands] Executing testServerConnection 
2017-09-20 15:19:28 [ INFO  ] JS: [Commands] Executing testServerConnection 
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] Active connection to "?th??" lost authorization 
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] Possible connection error for ?th??, retrying connection tests 
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] Testing all 4 connection(s) for ?th?? 
2017-09-20 15:19:28 [ INFO  ] JS: [Commands] Executing testServerConnection 
2017-09-20 15:19:28 [ INFO  ] JS: [Commands] Executing testServerConnection 
2017-09-20 15:19:28 [ INFO  ] JS: [Commands] Executing testServerConnection 
2017-09-20 15:19:28 [ INFO  ] JS: Cache overflow, size: 149 
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] Testing connection for ?th?? at http://127.0.0.1:REDACTED 
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] Testing connection for ?th?? at https://REDACTED.REDACTED.plex.direct:REDACTED 
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] Testing connection for ?th?? at https://REDACTED.REDACTED.plex.direct:REDACTED 
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] ?th?? is unavailable at https://REDACTED.REDACTED.plex.direct:REDACTED (Status 0) 
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] Prevented fallback to insecure connection for ?th?? 
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] Prevented fallback to insecure connection for ?th?? 
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] ?th?? connected at https://REDACTED.REDACTED.plex.direct:REDACTED 
2017-09-20 15:19:28 [ INFO  ] JS: [Servers] Found all servers = plex.tv, ?th?? 
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] ?th?? is unauthorized at http://127.0.0.1:REDACTED (Status 401) 
2017-09-20 15:19:29 [ DEBUG ] HelperLauncher.cpp @ 52 - Connecting to helper 
2017-09-20 15:19:29 [ DEBUG ] HelperLauncher.cpp @ 100 - Failed to connect to helper: "QLocalSocket::connectToServer: Invalid name" 
2017-09-20 15:19:29 [ DEBUG ] HelperLauncher.cpp @ 158 - Launching helper: "/usr/local/bin/pmphelper" 
2017-09-20 15:19:30 [ DEBUG ] HelperLauncher.cpp @ 52 - Connecting to helper 
2017-09-20 15:19:30 [ DEBUG ] HelperLauncher.cpp @ 100 - Failed to connect to helper: "QLocalSocket::connectToServer: Invalid name" 
2017-09-20 15:19:30 [ DEBUG ] HelperLauncher.cpp @ 158 - Launching helper: "/usr/local/bin/pmphelper" 
2017-09-20 15:19:30 [ DEBUG ] InputComponent.cpp @ 160 - Input received: source: "Keyboard" keycode: "Return" : InputBase::InputkeyState(KeyDown) 
```

**Comment by mseeley** [comment] 2017-09-26 02:34
@Enigma0 thank you for the logs. This is some odd stuff:

```
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] Active connection to "?th??" lost authorization 
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] Possible connection error for ?th??, retrying connection tests 
2017-09-20 15:19:28 [ INFO  ] JS: [Connections] Testing all 4 connection(s) for ?th?? 
```

By chance, have you tried to Sign Out/shut down PMP/restart PMP/Sign In again? The "No Soup for You!" is a cheeky authorization failure message. It could be there's a token mismatch between your server and the player. I'm unsure how you could have been bit by this but the teethmarks seem to line up.

**Comment by Enigma0** [comment] 2017-09-26 13:47
@mseeley I'll give that a try. I can access everything else other than playlists.

**Comment by Enigma0** [comment] 2017-09-27 22:17
@mseeley That did not work - same issue.

**Comment by c2dalark** [comment] 2017-09-28 21:44
@mseeley I'm also having issues with playlists for Plex Home user accounts, when in TV Full Screen mode.
PMP is 2.1.1 on Windows 10. PMS is 3.19.2 on Debian.

Primary Plex account can access playlists either in TV Full Screen, or windowed/WebUI mode. The Home user can access playlists through the windowed/WebUI mode, but gets the authentication error when in Full Screen.

I see similar loss of authentication messages in the log when full-screened on the home user. Let me know if you want me to pull logs from either client or the server.

@Enigma0 Can you access playlists when not in Full Screen mode?

**Comment by Enigma0** [comment] 2017-09-28 21:47
@c2dalark If I switch to the desktop/web mode, playlists do work, yeah.

@mseeley I guess I forgot to add the bit myself but a managed Guest account is the only place I've tried using playlists in tv2.

**Comment by mseeley** [comment] 2017-10-16 23:28
Ah super interesting. Thanks for the bit about browsing as a managed guest account. I'll look into it.

**Comment by mseeley** [comment] 2017-10-17 00:08
I've confirmed that playlists aren't shared between home users. My primary and managed test users both have movie playlists which render in the movie-type dashboard. I did notice that after creating the playlist I had to restart PMS for the playlist to display on the dashboard. I believe this is a separate PMS hub cache invalidation issue.

I'm not much closer to understanding the symptoms here. If a playlist was somehow shared between users it's conceivable that requesting the playlist would show an authorization failure due to playlists not be shared between users. _If_ this is what's occurring then there's a bug in PMS resulting in playlists leaking between users.

@Enigma0 are you seeing a playlist owned by one user selectable in the dashboard of another user?

> Primary Plex account can access playlists either in TV Full Screen, or windowed/WebUI mode. The Home user can access playlists through the windowed/WebUI mode, but gets the authentication error when in Full Screen.

@c2dalark are you also seeing a playlist owned by one user selectable in the dashboard of another user? If not, are you running into an issue where a managed user cannot access their own playlist from the full-screen TV layout?

**Comment by Enigma0** [comment] 2017-10-17 00:21
@mseeley I am seeing playlists on a managed user that were created with that account. I see them in the dashboard fine but I cannot load them when selecting them. That's when I get the error message.

**Comment by mseeley** [comment] 2017-10-17 01:00
Hi @Enigma0. Looks like we've got this fixed in our upcoming release:

![managed-playlists](https://user-images.githubusercontent.com/30019/31641723-55277338-b282-11e7-91bd-fa7a344a4097.gif)

I went back to an early 2.0 release and was able to finally reproduce this issue. My managed user was unable to load any of their playlists.

Thanks for your help+patience on this. We'll get this fix out soon as possible.

**Closed by mseeley** 2017-10-17 01:00 UTC

**Comment by Enigma0** [comment] 2017-10-17 01:54
@mseeley Is the fix not yet in the tv2 branch?

I only have PMP running in Linux so there's no release package for that yet.

**Comment by Enigma0** [comment] 2017-10-17 01:57
@mseeley Still fails the same way in the tv2 branch.

**Comment by mseeley** [comment] 2017-10-23 19:46
Hi @Enigma0, we're in `tv2-2.2.0-rc`.

**Comment by Enigma0** [comment] 2017-10-24 13:49
@mseeley Do you mean `dist-2.2.0-rc` ? I'm not seeing `tv2-2.2.0-rc`.

**Comment by Enigma0** [comment] 2017-10-24 14:06
@mseeley I get a seg fault core dump when launching PMP from the `dist-2.2.0-rc` branch.
