### ISSUE TITLE
Switched Folder View Broken

### ISSUE THREAD

**Issue by tnitpc** [plexinc/plex-media-player#154] opened 2015-11-16 06:06 UTC
using plex media player preview version 2.4.36 on OS X Yosemite, tried to change to folder view on one of the sections and it all disappeared. cant get poster view back.

**Comment by tnitpc** [comment] 2015-11-16 06:08
[Plex Media Player.txt](https://github.com/plexinc/plex-media-player/files/35193/Plex.Media.Player.txt)

**Comment by dogonwheels** [comment] 2015-11-17 10:07
Please can you post a screenshot of what this looks like? Would be helpful to see where we stop rendering the view.

I don't see anything suspect in the logs - could you please retry and let me know what time you navigate to the folder view?

Thanks!

**Comment by tnitpc** [comment] 2015-11-17 12:48
Hi, This is what happens. I go into plex media player then click on tv shows. the first screenshot shows On Deck stuff. I now click on Browse All and this is where it goes wrong.
![screen shot 2015-11-17 at 8 33 00 pm](https://cloud.githubusercontent.com/assets/15865838/11211649/efa9ff9a-8d6b-11e5-8fe8-69684ccdeaeb.png)
![screen shot 2015-11-17 at 8 33 19 pm](https://cloud.githubusercontent.com/assets/15865838/11211658/fb19eb74-8d6b-11e5-8082-07211fe37b81.png)

Thanks! for checking this out. I have been using Plex for at least 3 years now and have worked
 most issues. fortunately i have not had any major issues. I like this new player, and am aware that it is a preview.

**Comment by tnitpc** [comment] 2015-11-17 12:55
I have tried things like removing plex media player and other files to do with it.

**Comment by tnitpc** [comment] 2015-11-17 14:31
all i did was change the view to folder.

**Comment by tnitpc** [comment] 2015-11-18 02:34
Just tried on Windows version and same thing happens. it was working fine till I go and change to Folder View, then it goes blank, and no way of getting it back.

**Comment by tnitpc** [comment] 2015-11-18 14:45
[image: Inline image 1][image: Inline image 2]

the same problem occurs on the windows version.

**Comment by dogonwheels** [comment] 2015-11-19 11:03
Hmm. I'm stumped! Could I be a pain and ask to share your server temporarily to debug? I'm 'Dom C' (including the space). Thanks!

**Comment by tnitpc** [comment] 2015-11-19 15:46
I have shared it. Im not sure how you can debug that way. I tried re installing the app on mac and windows to see if it returns. No such luck. I also have a section called 0 that it wont let me clean or delete.
Hope this helps. 

Sent from Outlook




On Thu, Nov 19, 2015 at 3:03 AM -0800, "Dom Crayford" <notifications@github.com> wrote:












Hmm. I'm stumped! Could I be a pain and ask to share your server temporarily to debug? I'm 'Dom C' (including the space). Thanks!

**Comment by tnitpc** [comment] 2015-11-19 15:46
Thanks for helping, by the way.

Sent from Outlook




On Thu, Nov 19, 2015 at 3:03 AM -0800, "Dom Crayford" <notifications@github.com> wrote:












Hmm. I'm stumped! Could I be a pain and ask to share your server temporarily to debug? I'm 'Dom C' (including the space). Thanks!

**Comment by dogonwheels** [comment] 2015-11-20 15:34
Thanks for sharing this - I'm seeing a server error - `http://YOURIP:32400/library/sections/20/folder?type=2&sort=originallyAvailableAt:desc&X-Plex-Container-Start=0&X-Plex-Container-Size=32&X-Plex-No-Cache=14480334787401488&X-Plex-Product=Plex%20TV&X-Plex-Version=2.4.36&X-Plex-Client-Identifier=1qpo6ogpzry919k9&X-Plex-Platform=Chrome&X-Plex-Platform-Version=46.0&X-Plex-Device=Unknown%20Manufacturer%20%28OSX%29&X-Plex-Device-Name=Plex%20for%20Unknown%20Manufacturer%20%28OSX%29&X-Plex-Token=XXX` - please can you grab your PMS log when you see this issue?

I see the same issue when using Plex Web to view you TV section by folder.

**Comment by tnitpc** [comment] 2015-11-22 02:24
[Plex Media Server.txt](https://github.com/plexinc/plex-media-player/files/40967/Plex.Media.Server.txt)

**Comment by dogonwheels** [comment] 2015-11-23 10:03
Please enable verbose logging, attach a new log, and let me know the time you saw the issue - sorry, should have said beforehand!

**Comment by tnitpc** [comment] 2015-11-25 03:20
Hi,
I have turned on verbose logging on and attached two logs which record me going to the tv section where the failure occurs. hope this helps. the time is 11:03:27 look from bottom up to 11:03.
[Plex Media Server.txt](https://github.com/plexinc/plex-media-player/files/43454/Plex.Media.Server.txt)
[Plex Media Player.txt](https://github.com/plexinc/plex-media-player/files/43455/Plex.Media.Player.txt)

Thanks

**Comment by tnitpc** [comment] 2015-11-25 03:22
I don't seem to be able to find that error. is the log called something else? I'm not sure if I got the right one.

**Comment by tnitpc** [comment] 2015-11-25 04:39
Some good news. I tried to fix the "0" Section in my Library that would not delete. didn't have much luck, then i discovered this on plex's site https://support.plex.tv/hc/en-us/articles/201100678-Repair-a-Corrupt-Database
I did this and backed up the db file as suggested. at first it did say there was errors. so ran the other commands. restarted server hoping my library was not gone. made last attempt at deleting the library, when it actually deleted. amazed by this I thought maybe this would also fix "folder view issue" checked it out and bam! this brought the view back and my tv content in Plex Media Player Preview.
here is the terminal output. 

[Terminal log.txt](https://github.com/plexinc/plex-media-player/files/43481/Terminal.log.txt)

**Comment by tnitpc** [comment] 2015-12-01 05:23
Hey,

did you see the latest on github.

**Comment by firasdib** [comment] 2016-02-08 12:09
Hey, sorry for the delay. Is this still an issue? Did anyone ever figure out how to reproduce it?

**Comment by tnitpc** [comment] 2016-02-09 00:50
Hi, thanks for getting back to me. No it could not be reproduced. I managed to run plex check script from support and it fixed the plex server. 

Sent from Outlook Mobile




On Mon, Feb 8, 2016 at 4:09 AM -0800, "Firas Dib" <notifications@github.com> wrote:












Hey, sorry for the delay. Is this still an issue? Did anyone ever figure out how to reproduce it?

**Comment by firasdib** [comment] 2016-02-11 09:20
In that case I will close the issue down, if you experience the same issue again, feel free to reopen it :smile:

**Closed by firasdib** 2016-02-11 09:20 UTC
Labels: component:web, priority:high

**Comment by rsanch1** [comment] 2016-02-29 00:32
I did the same on Plex Media Player on Win 10.  I was curious what the folder view was going to show as, luckily it was on my kids user profile.  It did not affect my profile.  I'll try deleting the user and then re-adding it.
