### ISSUE TITLE
PMP UI Not Scaling Properly On External Monitor OS X 10.11.3 in 1.0.4

### ISSUE THREAD

**Issue by vladashram** [plexinc/plex-media-player#231] opened 2016-02-08 22:35 UTC
As a note, the UI scaling in 1.0.3 worked fine on my setup.

Setup: Macbook Pro Retina 11,3 Running OS X 10.11.3 and an ASUS VS247 monitor connected via HDMI

This is how Plex Media Player displays in fullscreen with my Built-In monitor(Native resolution:2880x1800, scaled to 1920x1200). It displays this way, whether or not the monitor is set as my main. A similar view is seen in Windowed-Mode, with proper scaling. It works at a variety of resolutions including the default 1440x900. 
![screen shot 2016-02-08 at 2 15 21 pm](https://cloud.githubusercontent.com/assets/7348173/12901253/69732592-ce6f-11e5-88cf-35270a02bbf6.png)

This is how Plex Media Player displays in fullscreen with my external ASUS VS247 monitor(Native resolution: 1920x1080). It displays this way, whether or not the monitor is set as my main. A similar view is seen in Windowed-Mode, with dysfunctional scaling above 1280x720. 
It works only if set to 1280x720.
![screen shot 2016-02-08 at 2 06 26 pm 2](https://cloud.githubusercontent.com/assets/7348173/12901023/1141654c-ce6e-11e5-9528-508e78b32d50.png)

Here is the Log
http://pastebin.com/jErD0VJB

EDIT:
I should mention, that video playback scales normally on both displays at any tested resolution.

**Comment by tru** [comment] 2016-02-09 06:23
The UI currently only supports 16:9 aspect ratio. This is most likely what you see, we add the black border to compensate.

**Comment by vladashram** [comment] 2016-02-13 02:13
It is the 16:9 that isn't working though.

**Comment by tru** [comment] 2016-02-14 07:46
I wonder if it has something to do which displayed as your primary one (when you setup the displays you can drag the top bar to either monitor) and if that makes the devicePixelRatio set differently between Qt and WebEngine. Can you try to set the external display to the primary one and see if it fixes the issue?

**Comment by vladashram** [comment] 2016-02-14 08:41
@tru Yeah I suspected the same thing. That PMP was for some reason detecting my main monitor and suing that for scaling. However, when setting the external as my main it made no difference. I mentioned that in my initial post, just above the second image.
"It displays this way, whether or not the monitor is set as my main."

**Comment by tru** [comment] 2016-02-14 09:02
Weird, because we can't reproduce it here. Can you let us know a bit more about your setup and hardware? Also OS versions etc?

**Comment by vladashram** [comment] 2016-02-16 03:43
It seems there is someone else with the same issue.
https://github.com/plexinc/plex-media-player/issues/237

My hardware is the Macbook Pro Retina 11,3 late-2013 with a dedicated NVIDIA Geforce GT 750M and the external monitor is the ASUS VS247 monitor connected via HDMI. 
OS version in Mac OS X El Capitan 10.11.3. I will provide more information in a few days, I had to send it in for a replaced panel(a few pixels burned out).

**Comment by ccl2of4** [comment] 2017-04-23 03:37
I am having this issue as well. On older versions of plex-media-player, things were working okay, but something within the past ~6 months completely borked the resolution for me.

* OS: Arch Linux
* Kernel: x86_64 Linux 4.10.9-1-ARCH
* DE: xfce4
* WM: xfwm4
* Monitors:
  * 1920x1080 HDMI (x1)
  * 1920x1080 DVI (x2)

![screenshot_2017-04-22_22-32-31](https://cloud.githubusercontent.com/assets/8164297/25310516/9aee84a4-27ab-11e7-93a0-dcc0ba13481b.png)

**Comment by wm4** [comment] 2017-04-24 11:55
Hm, I thought I fixed something like this recently.

Does any of this fix it:
- toggling fullscreen a few times
- going into windowed mode and resizing the window manually a few times

**Comment by ccl2of4** [comment] 2017-04-24 13:07
@wm4 Those workarounds _used_ to work for me, at least a few months back.

I _think_ they stopped working sometime around when I upgraded from 1.2.3 -> 1.2.4

When time permits, I will try downgrading back to 1.2.3 (and maybe a couple earlier versions too) to see if it was in fact a recent update that broke things.

**Comment by ccl2of4** [comment] 2017-05-06 18:03
I played around with installing different versions of PMP to try to find when exactly it was that the workaround (toggling fullscreen multiple times to get it to scale correctly) stopped working.

I installed 1.3.x, 1.2.x, and 1.1.x versions. The workaround did not work on any of these versions. This leads me to believe that it was not a coding change in PMP that caused it to stop working, but rather a change in the display server or window manager I'm using.

But still, if toggling fullscreen multiple times was what it took to get the UI to scale correctly, that sounds like something rather fragile that I am not surprised eventually stopped working.

PMP in fullscreen/TV mode it basically unusable for me because of this issue :disappointed:

**Comment by Collinthegeek** [comment] 2017-06-16 20:55
I have the same issue as @ccl2of4.
Fedora 25
pmp version: 1.3.2.dev-git
1920x1080p HDMI

**Comment by Collinthegeek** [comment] 2017-06-16 20:55
@ccl2of4 Are you on wayland or xorg?

**Comment by ccl2of4** [comment] 2017-06-16 22:16
I'm xorg.

@Collinthegeek See [this thread](https://github.com/plexinc/plex-media-player/issues/557) and my comment at the bottom for more discussion about this.

**Comment by Collinthegeek** [comment] 2017-06-16 22:18
I checked and there's no difference between the two anyway. It works
properly when started in standalone mode from the console but not when
launched in gnome.

**Comment by LongChair** [comment] 2018-04-11 15:41
@vladashram : is this still relevant in recent builds ? or can we close this ?

**Comment by LongChair** [comment] 2018-04-17 15:09
Closing due to the lack of feedback, feel free to reopen if needed.

**Closed by LongChair** 2018-04-17 15:09 UTC
Labels: stat:need-feedback
