### ISSUE TITLE
Distorted video upon resume

### ISSUE THREAD

**Issue by juicez** [plexinc/plex-media-player#330] opened 2016-05-03 02:48 UTC
Video playback is distorted and freezes upon resuming media yet audio continues to play fine. Log file and screenshot are attached. When this occurs, the log file reports the following error:

"Error when calling vdp_video_mixer_render: An invalid handle value was provided."

Version: PMP 1.1 .0 embedded
Hardware: ASUS EeeBox EB1033-B0100 (1.86 GHz Atom D2550, Nvidia GeForce 610M)

**(screenshot)**
![pmp video distortion](https://cloud.githubusercontent.com/assets/70870/14973519/c140151c-10b6-11e6-8486-0040e3ed4a48.jpg)

**(log file)**
[plexmediaplayer.zip](https://github.com/plexinc/plex-media-player/files/246240/plexmediaplayer.zip)

Issue does not occur while running OpenPHT or Kodi.

**Comment by wm4** [comment] 2016-05-03 11:24
I can't reproduce this.

The issue is with nvidia hardware decoding (i.e. vdpau). It can "preempt" the display on events such as switching display modes or virtual terminals. When this happens, the player needs to detect this and recreate the hardware decoder state.

Normally this is done, and when I switch virtual terminals on Linux, the player resumes properly.

Seems like in your case, display mode switching causes this. It randomly seems to fail to recover properly:
```
2016-05-02 20:54:30 [ ERROR ] PlayerComponent.cpp @ 448 - opengl-cb/vdpau-glx: Got display preemption notice! Will attempt to recover. 
2016-05-02 20:54:30 [ INFO  ] PlayerComponent.cpp @ 444 - opengl-cb/vdpau-glx: Recovered from display preemption. 
...
2016-05-02 20:54:31 [ WARN  ] PlayerComponent.cpp @ 446 - opengl-cb/vdpau-glx: Error when calling vdp_output_surface_destroy: An invalid handle value was provided. 
2016-05-02 20:54:31 [ DEBUG ] PlayerComponent.cpp @ 442 - opengl-cb: Texture for plane 0: 1920x1080 
2016-05-02 20:54:31 [ DEBUG ] PlayerComponent.cpp @ 442 - opengl-cb: Reinit rendering. 
2016-05-02 20:54:31 [ WARN  ] PlayerComponent.cpp @ 446 - opengl-cb/vdpau-glx: Error when calling vdp_video_mixer_render: An invalid handle value was provided. 
```

Are there any special circumstances which trigger this?

**Comment by wm4** [comment] 2016-05-03 11:41
Ah, never mind, I was able to reproduce it now.

**Comment by wm4** [comment] 2016-05-03 11:57
Most likely fixed via https://github.com/mpv-player/mpv/commit/eefe7ad28bceccd509d389dc4dba465467231fb1

PMP will include this fix whenever we make a new build that includes updated deps. I'm not sure when this will be.

Disabling hardware decoding should work around this bug until then.

**Closed by wm4** 2016-05-03 11:57 UTC
