### ISSUE TITLE
PMPhelper does not terminate

### ISSUE THREAD

**Issue by XenonPK** [plexinc/plex-media-player#464] opened 2016-12-02 13:41 UTC
The OS is Windows 10 (in my case), and when PMP terminates, the helper stays running on the background.
It has been reported in the [steam community forums](https://steamcommunity.com/discussions/forum/1/412448792352067707/) too, as it breaks usability when launching from steam big picture mode.

**Comment by wm4** [comment] 2016-12-02 13:46
This is as intended - though interfering with Steam is of course not intended.

Not sure what we can do to make Steam stop thinking that it's still running.

**Comment by tru** [comment] 2016-12-02 13:51
Add an option to directly quit the helper when the main app quits maybe?

**Comment by tru** [comment] 2016-12-02 13:53
or a least faster than whatever it's set to now.

**Comment by XenonPK** [comment] 2016-12-02 14:02
I don't think leaving a process running after the main app is closed is good policy.
I'm not saying it's anything serious like a memory leak or that I need the 1.5 mb of ram, that's not it, it's just, a bad way of handling things.
Does it really need to be running when the player is not being used?

**Comment by tru** [comment] 2016-12-02 20:00
The point of it is to stay behind and make sure a crashdump is not written (which happens async from the main process quitting).

**Comment by LongChair** [comment] 2018-04-10 16:30
Closing this as it is intended

**Closed by LongChair** 2018-04-10 16:30 UTC
