### ISSUE TITLE
PMP Starts then never Displays - Ubuntu

### ISSUE THREAD

**Issue by pbuchko** [plexinc/plex-media-player#553] opened 2017-04-27 15:14 UTC
Built PMP following the build directions for Ubuntu

When starting the application it launches, appears to start and run however no display shown

paul@htpc:~$ plexmediaplayer
libpng warning: iCCP: known incorrect sRGB profile
Logging to /home/paul/.local/share/plexmediaplayer/logs/plexmediaplayer.log
Logging to /home/paul/.local/share/plexmediaplayer/logs/pmphelper.log
[20581:20606:0427/110318:ERROR:nss_ocsp.cc(610)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
[20581:20606:0427/110318:ERROR:nss_ocsp.cc(610)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
[20581:20606:0427/110318:ERROR:nss_ocsp.cc(610)] No URLRequestContext for NSS HTTP handler. host: crl4.digicert.com
[20581:20606:0427/110318:ERROR:nss_ocsp.cc(610)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
[20581:20606:0427/110318:ERROR:nss_ocsp.cc(610)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
[20581:20606:0427/110318:ERROR:nss_ocsp.cc(610)] No URLRequestContext for NSS HTTP handler. host: crl4.digicert.com

There are 2 ERRORS in the log file:

017-04-27 11:03:09 [ ERROR ] InputLIRC.cpp @ 82 - LIRC Socket Error :  QLocalSocket::ServerNotFoundError

2017-04-27 11:03:09 [ ERROR ] DisplayManager.cpp @ 47 - DisplayManager : unable to retrieve main display

Using OpenBox Desktop, other display apps such as FireFox work fine

paul@htpc:~/.local/share/plexmediaplayer/logs$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

any ideas appreiated
[pmplog.txt](https://github.com/plexinc/plex-media-player/files/962050/pmplog.txt)

**Comment by wm4** [comment] 2017-04-27 16:29
Duplicate of #470, I think.

**Comment by wm4** [comment] 2017-04-27 16:29
What makes me think that is this, btw:
```
2017-04-27 11:03:09 [ DEBUG ] KonvergoWindow.cpp @ 784 - Screen 0 QScreen(0x21cbe70, name="HDMI-1") QRect(0,0 -2147483648x-2147483648) QRect(0,0 -2147483648x-2147483648) active: true selected: false 
```
Clearly broken by Qt.

**Closed by wm4** 2017-04-27 16:29 UTC

**Comment by pbuchko** [comment] 2017-04-28 11:21
Confirmed duplicate, `--scale-factor=1`  allows the window to render

FYI - Tried downgrading Qt to 5.7.0 and seeing the same behavior of the window not rendering unless scale factor is set
