### ISSUE TITLE
PMP Full Screen does not persist after display disconnect/reconnect

### ISSUE THREAD

**Issue by d1vanloon** [plexinc/plex-media-player#609] opened 2017-09-03 22:35 UTC
## Environment

Plex Media Player 2.1.0 running on Windows 10 v.1703. The media PC is connected via HDMI to an A/V receiver, which is connected to the TV.

## Steps to Reproduce

Run Plex Media Player in full-screen mode. Turn off the TV and A/V receiver. Wait a moment, then turn on the TV and A/V receiver.

## Expected behavior

Plex Media Player is displayed in full-screen mode and takes up the entire screen.

## Actual behavior

Plex Media Player does not take up the entire screen. The app seems to be shifted to the left by about 1/4 of the screen and is scaled down.

## Workaround

After turning on the TV and A/V receiver, sign in to Plex Media Player, go to Settings > Main and check Full Screen again.

## Comments

This was not an issue on the previous version of Plex Media Player prior to the v.2 update. I can acquire logs, screenshots, etc. if needed.

**Comment by wm4** [comment] 2017-09-04 10:57
You could try the `forceAlwaysFS` in plexmediaplayer.conf, but no idea if it helps.

**Comment by d1vanloon** [comment] 2017-09-22 02:21
I enabled that option to see if it would help. Now, when the screen is turned back on, PMP is scaled up several times so that only the top left corner of the application is shown, but it is zoomed to take up the entire screen. This issue remains open.

**Comment by wm4** [comment] 2017-09-22 04:02
Try the test builds and instructions provided around here: https://forums.plex.tv/discussion/comment/1507210/#Comment_1507210

**Comment by d1vanloon** [comment] 2017-09-26 21:50
I installed build 698 and tested with an without the `forceAlwaysFS` option. Without the option, it behaves as originally reported and is no longer full-screen after restarting the A/V receiver. With the option enabled, PMP is still scaled up dramatically so that only the top left corner of the UI is visible. This is what I see after turning my A/V receiver off and back on again:

![screenshot](https://user-images.githubusercontent.com/9598082/30885798-58b534fc-a2da-11e7-867f-7166af739ce8.png)

Of course, the UI is useless at this point and I have to pull out the keyboard/mouse and restart the app.

Glancing through the logs, I see that PMP detects a screen size change to 1024x768 when the A/V receiver turns off, then it detects another screen size change back to 1920x1080 when the A/V receiver turns back on. The logs don't mention anything about scaling up several hundred percent.

**Comment by mseeley** [comment] 2017-09-27 00:11
@d1vanloon would you mind searching our your `storage.json` (it's in the same directory at `plexmediaplayer.conf`? In the storage file we store information about the window's position and size. For instance here's mind:

```
"state":{"geometry":{"height":957,"width":1281,"x":0,"y":22}
```

Would you mind getting PMP into that massively over zoomed state then copy-past the `state` information here? It'll help us determine if the UI is scaling up to a massively wide window or if the UI's scaling is broken.

**Comment by d1vanloon** [comment] 2017-09-28 01:11
Here's my `state` JSON object when the UI is scaled up in that manner:

        "state": {
            "geometry": {
                "height": 493,
                "width": 956,
                "x": 0,
                "y": 17
            },
            "lastUsedScreen": "\\\\.\\DISPLAY1"
        }

This is actually *not* different from the `state` object when the application is at its normal scaling.

Again, this is on a 1920x1080 display.

When scaled, the window is actually larger than the display - I can move the PMP window around via the Windows control (right-click on taskbar icon > Move) and see that the application extends past the edges of the screen.

**Comment by xiconfjs** [comment] 2018-02-26 17:58
Problem is still valid. Any more information from developer side needed? Dumps, log files, configs?

**Comment by LongChair** [comment] 2018-02-27 05:36
I guess a full log of the full process could help :

- Start PMP with TV / AVR on
- make sure it's scaled properly
- turn off TV / AVR.
- turn it back on (that's where the problem is expected if i got that correctly).

Then please, get the logs and paste them here :)

**Comment by LongChair** [comment] 2018-04-10 18:28
Duplicate of https://github.com/plexinc/plex-media-player/issues/637
But would still be nice to have a log :)

**Comment by LongChair** [comment] 2018-04-17 16:34
@xiconfjs : ill close this oen as it's a duplicate, logs are still appreciated if you can get a chance to.
Let's follow this in #637.

**Closed by LongChair** 2018-04-17 16:34 UTC
Labels: component:host, stat:need-feedback
