### ISSUE TITLE
Steam Overlay isn't correctly drawn

### ISSUE THREAD

**Issue by Almamu** [plexinc/plex-media-player#527] opened 2017-02-21 20:55 UTC
Platform and OS Version: Windows 10 Anniversary Edition
Plex Media Player App Version: 1.2.2

When runing steam on top of Plex (for example using Big Picture to control everything from the Xbox Controller) the steam overlay can't be seen. It is possible to open it (and hear it on the background) but It wont render on any menu. It displays correctly if a video is playing on the Plesk App, so this leads me to think that the screen is not being redrawn unless needed (which sounds right to keep the gpu usage to a minimum).

Steps to reproduce:
- Enable OpenGL mode in PlexMediaPlayer
- Add the PlexMediaPlayer.exe to the steam shortcuts and run it from there
- Try to open steam interface on any plex menu and it wont come up. If you use Big Picture you can still hear how It's running on the background and can move through menus without seeing them.
- Hit ESC to close it and now play any fullscreen video
- Open the overlay and you'll notice this time it works

Would it be possible to force the GUI to be redrawn when overlay is openned or when the SteamOverlay.exe process is running so It's possible to use the whole steam interface?

**Comment by Enigma0** [comment] 2017-03-03 15:56
Same issue here.

**Comment by LongChair** [comment] 2018-04-10 19:11
@Almamu : is that still an issue with recent builds ?

**Comment by LongChair** [comment] 2018-04-16 06:08
@Enigma0 : could you tell me if this is still an issue with recent builds ?

**Comment by Enigma0** [comment] 2018-04-16 14:34
I'd have to set up a VM to test. I don't run any windows systems anymore.

Last I checked, the controls were the most inhibiting aspect to this kind of setup. The controls would go through but the screen would be 1 refresh behind so you never saw what you just did until you did something else.

**Comment by LongChair** [comment] 2018-04-16 17:12
Yeah I understand but I have no way to test this really.
We have been trying to clean up a little bit the issues recently as some are rather old, so that we can focus on the main remaining issues and keep going from there.
So wanted to close as much what can be so that we can get a fresh start :)

**Comment by Enigma0** [comment] 2018-04-16 17:47
So you don't have access to a windows system either? That's all you would need.

Everything else is just a few downloads and a minute of configuration.

**Comment by Almamu** [comment] 2018-04-17 09:17
Sorry I though that I had already answered to this. I'll look into it today because i have to update the environment, give me 5-6 hours to get home and I'll check it.

**Comment by LongChair** [comment] 2018-04-22 09:52
@Almamu : any update on this ?

**Comment by LongChair** [comment] 2018-05-03 06:18
@Almamu : Please try the build below which includes some Windows opengl / angle fix.

https://www.dropbox.com/s/w7neafa3ymv86mk/PlexMediaPlayer-2.10.0.854-c1633f57-windows-x64.exe?dl=0

Thanks to let me know if this fixes the issue above. 
I'll close this in a few days if i don't have feedback as i have no way to reproduce this.

**Comment by LongChair** [comment] 2018-05-07 16:12
Closing this due to the lack of feedback, feel free to reopen if needed.

**Closed by LongChair** 2018-05-07 16:12 UTC
Labels: component:host, stat:need-feedback
