### ISSUE TITLE
PMP completely unresponsive to input after pressing back on "Playing Next" screen

### ISSUE THREAD

**Issue by dan-the-man-nz** [plexinc/plex-media-player#732] opened 2018-05-12 21:29 UTC
### Test environment
**PMS Version:**  1.13.0.5023
**PMP Version:**   2.10.0.849-e02dbeca
**Platform (Windows/OSX/Embedded):**  Windows

### Steps to reproduce  (it does not happen every time unfortunately)
1. Finished an episode, "Playing Next" gui came up (its not set to auto play next episode i have to manually play it)
2. pressed back as i didnt want to watch

### Current behavior

3. PMP went back to the "PREPLAY SCREEN - edit" this view was incomplete with the episodes listed at the bottom of the screen only showed 5 episodes or so, should be 20+,  and was completely unresponsive to input, i could hear  the sound for each action/keypress, but no auction in the gui, had to force quit PMP

### Expected behavior

1. PMP should respond to input.

in the attached log, the issue starts at  2018-05-12 22:51:19

the log is then full of this
```
2018-05-12 22:51:19 [ INFO  ] JS: [Keys] Rescuing focus` 
2018-05-12 22:51:19 [ DEBUG ] InputComponent.cpp @ 69 - Emit input action (autorepeat): ("right") 
2018-05-12 22:51:19 [ INFO  ] JS: [Keys] No event publisher accepted `[
```
and 
```
2018-05-12 22:51:20 [ INFO  ] JS: [Keys] Rescuing focus` 
2018-05-12 22:51:20 [ DEBUG ] InputComponent.cpp @ 160 - Input received: source: "Keyboard" keycode: "Right" : InputBase::InputkeyState(KeyUp) 
2018-05-12 22:51:21 [ DEBUG ] InputComponent.cpp @ 160 - Input received: source: "Keyboard" keycode: "Backspace" : InputBase::InputkeyState(KeyDown) 
2018-05-12 22:51:21 [ DEBUG ] InputComponent.cpp @ 160 - Input received: source: "Keyboard" keycode: "Backspace" : InputBase::InputkeyState(KeyUp) 
2018-05-12 22:51:21 [ DEBUG ] InputComponent.cpp @ 180 - "Emit input action (short):" "back" 
2018-05-12 22:51:21 [ INFO  ] JS: [Keys] No event publisher accepted `[
```
as i attempt to regain focus
[PlexMediaPlayerBuggered.log](https://github.com/plexinc/plex-media-player/files/1997951/PlexMediaPlayerBuggered.log)

**Comment by LongChair** [comment] 2018-05-13 05:14
dupplicate of https://github.com/plexinc/plex-media-player/issues/731

**Comment by markus101** [comment] 2018-05-16 21:35
Reopening it, as I don't currently think this is related to #731.

> PMP went back to the series view

Not sure which view you mean here, whether it's the series list, or pre-play screen.

**Comment by dan-the-man-nz** [comment] 2018-05-16 21:38
sorry, that is not clear, yes it would be the preplay screen, with the season episodes at the bottom

example

![image](https://user-images.githubusercontent.com/906806/40145457-f73496f8-59b5-11e8-8b1e-087180ac9004.png)

**Comment by dan-the-man-nz** [comment] 2018-05-16 21:49
here is another log, from a different machine from last night, same issue.

finished at episode, was at the playing next screen, pressed back,
got back to the preplay screen, then PMP completely unresponsive.

revelant part from this machines log
```
2018-05-16 23:45:22 [ INFO  ] JS: [Metrics] Updating session last interaction time 
2018-05-16 23:45:22 [ INFO  ] JS: [Metrics] Updating session last interaction time 
2018-05-16 23:45:28 [ DEBUG ] InputComponent.cpp @ 160 - Input received: source: "Keyboard" keycode: "Backspace" : InputBase::InputkeyState(KeyDown) 
2018-05-16 23:45:28 [ DEBUG ] CachedRegexMatcher.cpp @ 68 - No match for: "Backspace" 
2018-05-16 23:45:29 [ DEBUG ] InputComponent.cpp @ 160 - Input received: source: "Keyboard" keycode: "Backspace" : InputBase::InputkeyState(KeyUp) 
2018-05-16 23:45:29 [ DEBUG ] InputComponent.cpp @ 180 - "Emit input action (short):" "back" 
2018-05-16 23:45:29 [ INFO  ] JS: [Metrics] Updating session last interaction time 
2018-05-16 23:45:31 [ DEBUG ] InputComponent.cpp @ 160 - Input received: source: "Keyboard" keycode: "Down" : InputBase::InputkeyState(KeyDown) 
2018-05-16 23:45:31 [ DEBUG ] InputComponent.cpp @ 229 - Emit input action: ("down") 
2018-05-16 23:45:31 [ DEBUG ] InputComponent.cpp @ 160 - Input received: source: "Keyboard" keycode: "Down" : InputBase::InputkeyState(KeyUp) 
2018-05-16 23:45:31 [ DEBUG ] UpdaterComponent.cpp @ 52 - It has gone 7178 seconds since last update check. 
2018-05-16 23:45:32 [ DEBUG ] InputComponent.cpp @ 160 - Input received: source: "Keyboard" keycode: "Down" : InputBase::InputkeyState(KeyDown) 
2018-05-16 23:45:32 [ DEBUG ] InputComponent.cpp @ 229 - Emit input action: ("down") 
2018-05-16 23:45:32 [ INFO  ] JS: [Keys] No event publisher accepted `[
  "down"
]` 
2018-05-16 23:45:32 [ DEBUG ] InputComponent.cpp @ 160 - Input received: source: "Keyboard" keycode: "Down" : InputBase::InputkeyState(KeyUp) 
2018-05-16 23:45:33 [ DEBUG ] InputComponent.cpp @ 160 - Input received: source: "Keyboard" keycode: "Up" : InputBase::InputkeyState(KeyDown) 
2018-05-16 23:45:33 [ DEBUG ] CachedRegexMatcher.cpp @ 68 - No match for: "Up" 
2018-05-16 23:45:33 [ DEBUG ] InputComponent.cpp @ 229 - Emit input action: ("up") 
2018-05-16 23:45:33 [ INFO  ] JS: [Keys] No event publisher accepted `[
  "up"
]` 
```
[PlexMediaPlayerROOMHTPC.log](https://github.com/plexinc/plex-media-player/files/2010953/PlexMediaPlayerROOMHTPC.log)

**Comment by dan-the-man-nz** [comment] 2018-05-23 06:41
same issue happened again, 

also, i notice on this preplay screen, when this issue happened, its missing episodes at the bottom.

![image](https://user-images.githubusercontent.com/906806/40407522-d67d751c-5eb8-11e8-8526-83b6ed8cc401.png)

**Comment by dan-the-man-nz** [comment] 2018-06-18 20:47
it had been a couple weeks since i had this, actually thought it might have been resolved in one of the newer PMP releases, but turns out not to be the case, had the same issue last night,

- resumed a episode, 
- finished a episode
- was on the playing next screen - pressed back
- was on the preplay screen, and like above in the arrow screenshot, there was many episodes missing, 
- PMP was non functional at that point on

here is the log from  2.12.1.871-6c71195e build date: 2018-06-15

[PlexMediaPlayer.log](https://github.com/plexinc/plex-media-player/files/2112934/PlexMediaPlayer.log)

**Comment by paulallison99** [comment] 2018-06-18 22:11
I haven't been able to repro this one yet - I'll have another look when I get back from vacation in a few days.

**Comment by dan-the-man-nz** [comment] 2018-06-19 00:39
understand, even i cannot reproduce it everytime either, not sure what the trigger is

enjoy the rest of your vacation

**Comment by markus101** [comment] 2018-06-19 01:34
When you do reproduce it, does that show/episode have extras?

I've run into an error which seems to be related to https://github.com/plexinc/plex-media-player/issues/731, but may also be the same thing you're seeing here.

**Comment by dan-the-man-nz** [comment] 2018-06-19 01:43
no trailers/extras, i dont have this turned on in PMS for the tv library, as shown below

i am quite sure every time this does happen, it is missing episodes in that bottom row on the preplay screen  like in the Doppleganger/Arrow screenshot above,  they are missing - only when this bug occurs. i can tell instantly before pressing any button its going to be broken when its missing those episodes, 


![image](https://user-images.githubusercontent.com/906806/41571196-280c7320-73c6-11e8-8e06-e8aee953faf8.png)

**Comment by dan-the-man-nz** [comment] 2018-06-24 05:10
happened again, on a different htpc to the machine logs above

log here   
[PlexMediaPlayer.log](https://github.com/plexinc/plex-media-player/files/2130476/PlexMediaPlayer.log)

a better screenshot showing the missing episodes when this issue happens.

![image](https://user-images.githubusercontent.com/906806/41816150-67356cb4-77d1-11e8-8c7b-ca98505d85b4.png)

**Comment by dan-the-man-nz** [comment] 2018-06-28 20:20
someone else on forum reporting same issue here

https://forums.plex.tv/t/pmp-2-6-up-to-2-13-bug-loss-of-selection-focus-after-stopping-playback/235208/3

**Comment by paulallison99** [comment] 2018-07-08 17:36
Sorry Dan I'm still having no luck reproducing this. I'll keep trying.

**Comment by paulallison99** [comment] 2018-08-08 10:27
@dan-the-man-nz we still can't reproduce this, but there is a way for you to log the web inspector console for it if you follow these steps:
https://gist.github.com/paulallison99/ca39142255d4ccee89e66ed00d87071a

If you can attach a console file to this GHI after the bug happens, it may give us something to go to reproduce/fix it, as the console may contain logs, warnis or errors related to it. Then we'll move it from the backlog back into active development.

**Comment by dan-the-man-nz** [comment] 2018-08-08 23:01
all good

i was just trying out those instructions, so if i can get it to happen again will know what i was doing

but when i go to console and try and save it, using the instruction below

- save it as a file, you simply right-click anywhere in the console, and then click Save as...

am i doing something wrong?

![image](https://user-images.githubusercontent.com/906806/43868807-809897a6-9bc3-11e8-9156-749daeba54b2.png)

**Comment by paulallison99** [comment] 2018-08-09 18:04
No you're right, that's my bad, that's a pity. Instead, you can try taking a screenshot of the newest logs, we should still see an error or warning logged.

**Comment by dan-the-man-nz** [comment] 2018-08-10 22:43
no worries, i have setup 3 machines with this, hopefully it will happen again, hasent happened for a while for me tho,

to be clear, you are interested in screenshots from the console tab right? no other tab in the developer tools is needed? elements, network etc

cheers

**Comment by paulallison99** [comment] 2018-08-11 10:37
Thanks Dan! Yep just the console tab is fine. If it doesn't happen again hopefully it means it was fixed by a code cleanup.

**Comment by dan-the-man-nz** [comment] 2018-08-25 06:43
hey Paul

havent been able to repeat it, i guess its been fixed by the cleanup mentioned

only once so far, did it look like it might happen, it didnt load all the episodes in the preplay screen at the bottom like the screenshots above, but i DIDNT loose focus when they  happened

happy to close this issue

**Comment by paulallison99** [comment] 2018-08-27 11:16
Thanks Dan. I'll close it and we can always re-open if you notice it again.

**Comment by dan-the-man-nz** [comment] 2018-09-12 19:27
hey @paulallison99 - can you reopen this

PMP  2.18.0.893-48795f25 build date: 2018-09-04 Windows 10x64

was watching IASIP - episode finished, play to preplay screen, episodes missing from the botttom and lost focus, couldnt do anything in PMP

i was able to grab the console tho :)

[PlexMediaPlayer.log](https://github.com/plexinc/plex-media-player/files/2376581/PlexMediaPlayer.log)
![developer_tools_-_filecprogram 20filesplex_2018-09-12_23-51-57](https://user-images.githubusercontent.com/906806/45448289-12643f00-b726-11e8-8149-6e0f0c9d0a43.png)
![developer_tools_-_filecprogram 20filesplex_2018-09-12_23-52-18](https://user-images.githubusercontent.com/906806/45448299-18f2b680-b726-11e8-8752-d2f4329e7a7c.png)
![image](https://user-images.githubusercontent.com/906806/45448367-4475a100-b726-11e8-8c4d-f6405de014dd.png)

**Comment by mseeley** [comment] 2018-09-12 19:57
@paulallison99 back to you.

**Comment by paulallison99** [comment] 2018-11-13 20:20
Have you seen this recently @dan-the-man-nz ? Apologies for the delay, still having no luck reproducing it :(

**Comment by dan-the-man-nz** [comment] 2018-11-13 20:42
approx a month ago, where i lost focus

was the data i captured above no help?

**Comment by paulallison99** [comment] 2018-11-13 20:47
I see that error every time we lose focus but it doesn't tell me why unfortunately. I think if I can finally repro the episodes going missing I can nail it.

**Comment by dan-the-man-nz** [comment] 2018-11-13 21:09
yea,

in the past, 5+ months ago, everytime the episodes would go missing at the bottom, 100% of the time it would have lost focus

but recently the last 2-3 months , i have seen it missing those episodes, but not loose focus.

but 100% of the time when it does loose focus, it is always missing some episodes at the bottom

**Comment by paulallison99** [comment] 2018-11-13 21:13
Thanks @dan-the-man-nz that makes sense!

**Closed** 2018-11-28 21:42 UTC
