### ISSUE TITLE
Frames dropping on OSX

### ISSUE THREAD

**Issue by bobbysteel** [plexinc/plex-media-player#257] opened 2016-03-07 22:12 UTC
After installing El Capitan OSX on a i7 Mac Mini, I'm getting semi-frequent stuttering video. Audio is fine but frames are dropping for maybe 500ms to 4 seconds in length.

I was able to track down the lines in the debug log. Basically getting a lot of these:
vo/opengl-cb: mpv_opengl_cb_draw() not being called or stuck.

Full log around the time of the stuttering.
http://pastebin.com/7FzSF8ka

Thoughts? Seems to be recurring and really hard to reproduce - generally after a fresh reboot it takes a day or so to recur, but it's entirely unpredictable.

**Comment by wm4** [comment] 2016-03-08 07:22
When these log messages appear, it means Qt isn't updating the screen (and the video) as the player requested.

**Comment by bobbysteel** [comment] 2016-03-08 09:35
Any suggestions on causes or a fix?
Thanks

**Comment by wm4** [comment] 2016-03-08 10:18
I'm wondering why it seems to be suddenly happening, but for now, no fix.

**Comment by wm4** [comment] 2016-03-08 10:18
PS: if you find a good way to reliably reproduce, that would help.

**Comment by bobbysteel** [comment] 2016-03-08 10:32
Unfortunately I've not found any to reliably reproduce yet. It feels memory-leaky - it takes a while to build up. With a fresh reboot, I can watch video for at least a few hours w/o repercussion. But the next day it will start behaving erraticly, but then correct itself too for a while. 

It was first noticeable when I upgraded to El Capitan a couple weeks ago, so perhaps an issue with the newest Intel driver in that release?

**Comment by bobbysteel** [comment] 2016-03-09 22:51
To provide some more background, restarting Plex seems to solve it. But it recurs after maybe 4-5 hours of video watching over a couple days. This is on a newer Mac Mini (late 2012) with integrated Intel 4000 graphics.

**Comment by macdo5** [comment] 2018-02-20 08:14
I have the exact same issue on arch linux. Opened terminal and ran tail -f ~.local/share/plexmediaplayer/logs/plexmediaplayer.log, noticed that once frame dropping stops, log file outputs this line 4-5 times:  
`2018-02-20 20:52:06 [ DEBUG ] PlayerComponent.cpp @ 583 - vo/opengl-cb: mpv_opengl_cb_draw() not being called or stuck.`  
Full (censored) log file:
[plexmediaplayer.log](https://github.com/plexinc/plex-media-player/files/1739295/plexmediaplayer.log)
Apologies in advance for necrobump, but is there any fix?

**Comment by LongChair** [comment] 2018-04-14 16:13
@macdo5 : frame dropping can have so many causes, usually because it wouldn't use proper hw decoding, bugged driver and such. there is not one single fix.
I'll close this issue as it's old and OSX related, if you need assistance on your framedropping we'd need a logfile.

**Closed by LongChair** 2018-04-14 16:13 UTC
Labels: component:mpv
