### ISSUE TITLE
Player : Settings of Media Player "Standard Layout" & Settings of "TV Layout" are conflicting

### ISSUE THREAD

**Issue by Ribero** [plexinc/plex-media-player#794] opened 2018-11-01 13:15 UTC
### Test environment
**PMS Version:** Version 1.13.9.5456
**PMP Version:** Version 3.71.1 
**Platform (Windows/OSX/Embedded):** macOS 10.13.6 / macOS 10.14

### Steps to reproduce

To reproduce the issue user will have to change settings in Media Player then activate TV layout, change settings there, then exit TV Layout...

Test case described and commented here:

**1/** Launch the Media Player and go to settings, select 24hours time format and Play Theme music and Save:
![screen_capture1](https://user-images.githubusercontent.com/2266264/47853053-da9c7e00-dddd-11e8-833c-991fbbcf7473.png)

**2/** Customize video settings and save:
![screen_capture2](https://user-images.githubusercontent.com/2266264/47853055-da9c7e00-dddd-11e8-8188-8560e2e5621a.png)

**3/** Activate the TV Layout. Observe that, by default, the top menu shows all available media types (Movies, Shows, Music...):
![screen_capture3](https://user-images.githubusercontent.com/2266264/47853057-da9c7e00-dddd-11e8-9994-60506764055a.png)

**4/** Customize **order** and **show/hide** status:
![screen_capture4](https://user-images.githubusercontent.com/2266264/47853058-da9c7e00-dddd-11e8-8155-8d7b2e7b572e.png)

**5/** Go to Video settings, observe that default settings are not coherent with the one choosen in **step 2**
![screen_capture5](https://user-images.githubusercontent.com/2266264/47853059-db351480-dddd-11e8-8560-8aa5a56ae212.png)

**6/** Customize video settings:
![screen_capture6](https://user-images.githubusercontent.com/2266264/47853060-db351480-dddd-11e8-9148-dc362ec125c0.png)

**7/** Go back to main menu and observe that settings are correctly taken into account (media type list & order): 
![screen_capture7](https://user-images.githubusercontent.com/2266264/47853061-db351480-dddd-11e8-99d8-e77edafda2a9.png)

**8/** Exit TV Layout and go back to Media Player General Settings, Observe that previous settings (**step 1**) are lost:
![screen_capture8](https://user-images.githubusercontent.com/2266264/47853062-db351480-dddd-11e8-888d-6e299be9e497.png)

**9/** Go to video settings, Observe that previous settings (**step 2**) are also lost:
![screen_capture9](https://user-images.githubusercontent.com/2266264/47853063-dbcdab00-dddd-11e8-80a0-dc8669a0a497.png)

**10/** Set, again, "Time Format" to 24hours:
![screen_capture10](https://user-images.githubusercontent.com/2266264/47853064-dbcdab00-dddd-11e8-8e62-bd46e6a3d884.png)

**11/** Activate TV Layout, observe that previous "Media Type" settings (order and show/hide status) are lost:
![screen_capture11](https://user-images.githubusercontent.com/2266264/47853065-dbcdab00-dddd-11e8-96bf-c22a827e03e0.png)

**12/** Observe that Media types settings are reset to default values:
![screen_capture12](https://user-images.githubusercontent.com/2266264/47853066-dbcdab00-dddd-11e8-8638-1dad30175bd6.png)

**13/** Video Settings are not lost but not consistent with settings observed in **step 9**
![screen_capture13](https://user-images.githubusercontent.com/2266264/47853067-dc664180-dddd-11e8-87de-cdf70445b3ad.png)

### Current behavior

1. Settings in "standard layout" seems to be conflicting with settings of "TV Layout". Settings are lost when switching from one layout to another.
2. Video settings are not consistent and coherent between "Standard layout" and "TV Layout". _Is here any interest to have different settings for both layout ?_

### Expected behavior

1. Video Settings should be consistent between different layouts "Standard Layout" and "TV layout"
2. Settings in "Standard Layout" should not overwrite settings of "TV Layout"
3. Settings in "TV Layout" should not reset "standard layout" settings
4. Specific layout settings should not be lost

**Comment by bouscram** [comment] 2018-11-11 17:14
Same behaviour for me.

**Comment by mseeley** [comment] 2018-11-26 22:05
Very correct, this is one of our long-standing sore points.

The settings are unfortunately not shared between the two layouts. Realistically it's _one application_ to a user although the implementation is structured more as _two applications_ without shared storage.

I appreciate your detailed report @Ribero. We understand this causes frustration although don't have capacity to address in the near-future. In the mean-time I'll leave this issue open for tracking.

**Comment by bouscram** [comment] 2018-11-26 22:39
I think the problem is not that settings are not shared (which can be understood), but that switching UI makes you lose the setting of the other one...

**Comment by Ribero** [comment] 2018-11-26 23:41
> I think the problem is not that settings are not shared (which can be understood), but that switching UI makes you lose the setting of the other one...

Correct. 
Sharing is a "nice to have feature", the loss of settings is probably more likely to be a defect.

**Comment by mseeley** [comment] 2018-11-27 02:12
> I think the problem is not that settings are not shared (which can be understood), but that switching UI makes you lose the setting of the other one...

I see better now what I missed initially. Yes that fubar that settings made in one layout are lost when switching layouts. Thanks for the polite reminder folks. We'll get this fixed up.

**Comment by mseeley** [comment] 2019-01-29 20:54
We lost sight of this for a while. We've recreated the issue and understand the problem. We're looking for possible fixes.

**Comment by MollyBe** [comment] 2019-07-13 17:29
Another frustrating bug related to this which hasn't been mentioned so far:

When switching to either TV mode or PC mode on PMP with any home user account it will reset the settings for ALL home user accounts. 

Thanks for keeping us updates mseeley.

**Comment by mseeley** [comment] 2021-02-08 21:35
This is a troublesome issue which we never fully disentangled. Our PMP update in development fully separates the Desktop and TV layouts into separate applications. It's not perfect for all users but aligns better with the "on my computer" and "on my HTPC" usage patterns. You can read more here: https://forums.plex.tv/t/plex-media-player-3-0-feedback/548889/131

With this in mind I'm closing this issue as won't fix.

**Closed by mseeley** 2021-02-08 21:35 UTC
