### ISSUE TITLE
Crash when two monitors are connected to two different GPUs on windows

### ISSUE THREAD

**Issue by swetty314** [plexinc/plex-media-player#9] opened 2015-10-20 21:34 UTC
Plex Media Player won't launch, process quits after about 1-2 seconds.  Log is below.

https://gist.github.com/swetty314/e55335954cb7b0e9e982

Windows 7 Pro x64

**Comment by wm4** [comment] 2015-10-20 21:39
Things to try:
- start PMP via the "Plex Media Player (DirectX)" start menu entry
- update graphics drivers

**Comment by swetty314** [comment] 2015-10-20 21:46
Tried both suggestions but having the same problem.

**Comment by wm4** [comment] 2015-10-20 21:50
Hm, kind of running out of ideas. If you're feeling adventurous, can you try to edit plexmediaplayer.conf (see https://support.plex.tv/hc/en-us/articles/207338798-Advanced-Configuration), and set the ``fullscreen`` and ``hardware_decoding`` settings to ``false``=

**Comment by swetty314** [comment] 2015-10-20 23:41
That also did not work.

Is there a 64bit version of the application?  The Download 64-bit button directs me to the x86 version, (PlexMediaPlayer-1.0.0.5-53192cb0-windows-x86).  Not sure if that would help.

**Comment by naisspas** [comment] 2015-10-20 23:48
Exactly the same problem, on Windows 8.1 x64 (approximatly the same logs, halt without error)

**Comment by rdurdle** [comment] 2015-10-21 00:00
So mine was doing the same, so i disabled my other two displays. One on an AMD card, one on the 2nd port of my nvidia.. and boom. Works perfect.

**Comment by rdurdle** [comment] 2015-10-21 00:02
Tried with just the AMD card disabled, and it works... but as soon as I tab out and enable my AMD display.. the app dies. Reverting back to PHT.

**Comment by naisspas** [comment] 2015-10-21 00:04
Thanks for your feedback, I will wait for another release :)

**Comment by tru** [comment] 2015-10-21 07:13
Interesting so there seems to be some kind of problem with the app starting and probing the display modes when you have multiple displays. Can you guys explain your setup a bit more, you have multiple screens connected to multiple graphics cards or what?

**Comment by naisspas** [comment] 2015-10-21 12:19
i5-2500 > Intel HD Graphics 2000 : 1 TV + 1 Monitor connected
AMD 6850 : 2 monitors connected

**Comment by wm4** [comment] 2015-10-21 12:40
So am I getting this right:
- connecting multiple screens to multiple graphics cards doesn't work
- connecting multiple screens to the same graphics card works

**Comment by swetty314** [comment] 2015-10-21 20:40
That seems to be the case.

I originally had a GTX 970 going to one monitor and a GTX 660ti going to the other and the app wouldn't start.  Connecting both monitors to the 970 allows the app to launch.

**Comment by gamjar** [comment] 2015-10-21 22:51
Same issue for me. Doesn't launch in Windows 10 with 2 monitor setup (one onboard, one dedicated AMD card). Unplugged onboard monitor and it launched with no issues.

**Comment by cr08** [comment] 2015-10-28 03:24
I am having the same issue here. My setup is on a switchable GPU laptop, AMD/Intel. However the current drivers are binary, ie: AMD only or Intel only. Not sure how this effects Plex. I do have two monitors attached. One via VGA, other HDMI/DVI.

**Comment by wm4** [comment] 2015-10-28 18:40
Build 1.0.1.42 installs a ``PlexMediaPlayer-NoChromiumGPU.bat``. Can anyone who is experiencing crashes try this? I don't know if it helps, just a stab in the dark.

**Comment by tru** [comment] 2015-10-29 08:15
Working on a windows setup at the office to be able to reproduce this issue this week.

**Comment by wchristian** [comment] 2015-10-29 14:25
> Build 1.0.1.42 installs a  PlexMediaPlayer-NoChromiumGPU.bat . Can anyone who is experiencing crashes try this?

No change.

**Comment by kayone** [comment] 2015-10-30 23:01
here is my setup:

HDMI connection to Intel HD Graphics 4600
Display Port connection to GTX 460

both displays are 1440x 2560

I can start the app if the only display connected is GTX 460, as soon as I activate the Intel Graphics it blows up.
_note:_ it doesn't even start if intel is the only display connected. I'll turn off the PC and remove the nvidia GPU completely and see if that helps.

**Comment by cr08** [comment] 2015-10-31 22:13
Originally I just did a direct install of 1.0.1.42 over 1.0.0.5. First off noticed it wasn't installing the ChromiumGPU bat file that other people have. Did a uninstall and then installed 1.0.1.42 straight away. Noticed it installed to the 64 bit program files directory this time and gave me the Chromium GPU bat file. Still no change though.

**Comment by Trahloc** [comment] 2015-11-01 03:02
Same issue, windows 10 64bit with nvidia 780 and 680, 4 monitor setup (3x dvi-d 1440p, 1x display port 4k)

**Comment by tru** [comment] 2015-11-02 15:49
I reproduced this in my setup today and I think I have a fix. Will push a nightly version that you guys can try.

**Comment by tru** [comment] 2015-11-02 19:22
Can anyone with this problem try this build: https://nightlies.plex.tv/directdl/plexmediaplayer/dist-ninja/1.0.2.45-f7da4ab2/PlexMediaPlayer-1.0.2.45-f7da4ab2-windows-x86_64.exe

Bonus points for testing frame rate switching as well and make sure that it switches correctly and to something that is "correct".

**Comment by kayone** [comment] 2015-11-02 19:31
can confirm `PlexMediaPlayer-1.0.2.45-f7da4ab2-windows-x86_64` fixed it on my machine. 

great work!

**Comment by naisspas** [comment] 2015-11-02 22:31
Works for me too !
Good job @tru :)

I have a little bug when I 'maximized' the window on one of my displays (TV hdmi), the interface 'shake' (but video played well). No bug in full screen.

**Comment by gamjar** [comment] 2015-11-02 22:46
Also launches for me. Having issues when full screen on one monitor but using programs on another. Not sure if it's related to this issue or another quirk on the initial release.

**Comment by naisspas** [comment] 2015-11-02 23:16
@gamjar :same issue with program minimizing itself when fullscreen and using another program.

**Comment by rdurdle** [comment] 2015-11-03 01:46
I'd like to be able to swap it to another monitor... but it seems to be
working :)

-- 
http://www.robdurdle.com
---
Would those of you in the cheaper seats clap your hands?
And the rest of you, if you'll just rattle your jewelry.
 - John Lennon

**Comment by kayone** [comment] 2015-11-03 02:04
I think this issue should be considered fixed (will wait for @tru to close it), please open a new issue for any other problems,

there is already an issue for app minimizing when losing focus https://github.com/plexinc/plex-media-player/issues/120

**Comment by tru** [comment] 2015-11-03 07:36
Thanks all for testing!

**Closed by tru** 2015-11-03 07:36 UTC
