### ISSUE TITLE
x264 10-Bit Playing @RaPi2

### ISSUE THREAD

**Issue by Massaguana** [plexinc/plex-media-player#109] opened 2015-10-31 12:56 UTC
Playing Movies with x264 10-Bit Enconding there are massiv green and blue artifacts in Picture... with PMP @Mac there are no problems

**Comment by wm4** [comment] 2015-10-31 13:10
RPI can't decode 10 bit, and we accidentally did not transcode it in the first release. But the second release should fix this. Can you confirm?

**Comment by Massaguana** [comment] 2015-10-31 13:15
No, same Problems with the second release...

**Comment by wm4** [comment] 2015-10-31 13:39
Right, it appears it's still broken. I just got another report that the RPI tries to decode HEVC in software, which is similarly wrong.

**Comment by wm4** [comment] 2015-10-31 13:43
Just for completeness, can you post your PMS version?

**Comment by Massaguana** [comment] 2015-10-31 13:44
Sure... PMS Version 0.9.12.18

**Comment by rcombs** [comment] 2015-10-31 17:00
We've caught at least one potential cause of this issue remaining in the second release. Could you post the media XML for a file that exhibits the issue, so I can make sure we're not missing anything else?

**Comment by Massaguana** [comment] 2015-11-07 18:34
with 1.0.2RC same issue

**Comment by mseeley** [comment] 2016-01-04 23:55
Looking through our current code the app should be refusing to direct play 10bit videos on the RPi2 (forces transcode). Anyone available to verify/close this issue? Thanks!

**Comment by OttoKerner** [comment] 2016-01-05 00:02
Can't recreate with latest ninja release of PMP-embedded on my RasPi 2.

**Comment by mseeley** [comment] 2016-01-05 00:03
Thanks @OttoKerner. Closing it out then.

**Comment by Massaguana** [comment] 2016-01-06 15:30
with 1.0.3 the issue are still there

**Comment by tru** [comment] 2016-01-06 15:34
Did you upgrade your PMS and re-analyze the file? There was a bug in the server that didn't classify the file correctly before.

**Comment by Massaguana** [comment] 2016-01-06 15:57
PMS runs with 0.9.15.0 and re-analyze is done, issue still there. Sorry.

**Comment by mseeley** [comment] 2016-01-06 19:04
Mysterious, thanks for the feedback.

**Comment by Massaguana** [comment] 2016-01-10 08:32
would help you a sample?

**Comment by Massaguana** [comment] 2016-01-12 16:57
Same issue with PMS 0.9.15.1 after re-analyze complete library...

**Comment by firasdib** [comment] 2016-01-14 11:07
Yes, a sample file would help to further investigate the issue.

**Comment by Massaguana** [comment] 2016-01-14 15:40
Here are two 5 minute Sample´s, one with HD resolution one with SD resolution:
https://www.dropbox.com/s/kj1uta6odm0va86/x264-10Bit%20SD%3AHD%20Sample.zip?dl=0

**Comment by Massaguana** [comment] 2016-01-23 12:00
Same issue with PMS 0.9.15.2 after re-analyze complete library...

**Comment by wm4** [comment] 2016-01-25 15:55
Consistently can't reproduce this. I've tried with PMP 1.0.4 (RC/ninja), and  PMS 0.9.15.1.

**Comment by Massaguana** [comment] 2016-01-25 16:38
did you test it with my Sample´s?

**Comment by wm4** [comment] 2016-01-25 17:36
Actually no, but the ones I tested were definitely 10 bit.

**Comment by Massaguana** [comment] 2016-01-26 07:48
My By there are different´s... my files are self encodet. wood you provide me an sample?

**Comment by OttoKerner** [comment] 2016-01-26 13:53
I could reproduce the issue with your sample files.
I even remuxed the HD sample and removed the 'header removal' compression. It got only worse.

That being said, there is not much point in using 10bit if you don't raise the number of reference frames. Even less so if the movie is not an animation movie. But that is just an aside.

**Comment by Massaguana** [comment] 2016-01-26 16:43
in my experience brings 10bit much in terms of file size / compressibility and better gradients in dark scenes.

**Comment by wm4** [comment] 2016-01-27 16:53
I can confirm the problem. I used PMS 0.9.15.2 (newest Plex Pass), added your sample files, refreshed the library, and attempted to play it on RPI with some 1.0.4 pre-release PMP/OE. And indeed, I see some green soup, typical for artifacts that happens when decoding 10-bit with an 8-bit only decoder. The worst of all, it was transcoding, but to 10 bit. Looking at the metadata also showed that PMS knew this file was using the "high 10" profile.

At the same time, I played some 10 bit file file from some other server, and it worked correctly (this was one of the tests I did before).

So what is going on? Is 0.9.15.2 _still_ too old? Did the fix not work? It seems to work sometimes, and sometimes not?

The sample files were detected as 10 bit by both ffprobe and mediainfo too, but PMS properly detected them anyway.

**Comment by Massaguana** [comment] 2016-01-27 17:55
So with my 10-bit movies it's always... maybay there are some special encoding Settings fault this sometimes yes oder no...
Are you Samples self encodet? You now the detail settings?
This are my Settings: x264-10bit --preset slow --crf 19.00 --profile high10 --psy-rd 1.00:0.15 --sar 1:1 --qpfile GENERATED_QP_FILE --deblock -1:-1 --non-deterministic --colormatrix bt709 --input-csp i420  --fps 25 --input-res 48x48 --output OUTPUTFILE -

Sometimes another preset or crf

**Comment by mseeley** [comment] 2016-01-28 02:55
We think we found the issue. The bit-depth limitation passed to PMS incorrectly enforced a bit-depth of 8. 

So, the app on the RPi2 will not direct play 10bit _and_ when asking the server to transcode the video we'll ask the server for an transcode with a bit-depth of 8.

I've committed the client fix. It should be picked up in the next PMP build.

**Comment by mseeley** [comment] 2016-02-09 07:06
Re-closing post the `bitDepth` casing fix.

**Closed by mseeley** 2016-02-09 07:06 UTC
Labels: component:web, priority:high, type:bug
