### ISSUE TITLE
PMP 1.0.1.42 - Problem playing music tracks

### ISSUE THREAD

**Issue by NedtheNerd** [plexinc/plex-media-player#85] opened 2015-10-29 16:24 UTC
Since the update to PMP i am having issues playing back music tracks in a Playlist, tracks will be skipped after displaying a message 'no audio or video data played', subsequent track(s) will play OK, then get the same error, no pattern to it.

The same tracks were playing fine on the previous release.

Plex Media Server PMS 0.9.12.18, however, I rolled PMS back to 0.9.12.17, still the same issue so the bug must be in PMP 1.0.1.42 as the same tracks played fine in PMP 1.0.0.5.

Log file can be found here https://forums.plex.tv/discussion/comment/1046538

**Comment by wm4** [comment] 2015-10-29 16:42
It appears we're getting ``video`` as media type from web-client when playing music. This must be a regression.

Additionally, the music file you played apparently contains a cover art picture. Since the media type is signaled as ``video``, the player tries to decode and display this picture. But apparently the picture's format is not marked correctly (claims it's PNG, but is something else), so decoding fails, and playback is aborted with an error. (A sample file would be appreciated. Then this could be fixed in FFmpeg.)

**Comment by wm4** [comment] 2015-10-29 16:43
CC @dogonwheels

**Comment by NedtheNerd** [comment] 2015-10-29 17:25
All cover art is loaded through iTunes, when I rip an album I also add cover art myself rather than let iTunes download it using the Get Info dialogue in iTunes.

I cannot add a music track to this issue as I do not have the correct rights.  Any suggestions?

**Comment by NedtheNerd** [comment] 2015-10-29 17:47
Just tested same 'unplayable' tracks on Plex for iOS and Plex HT on my MacBook Pro, all play without any issue.

They also play without issue on Rasplex running on both RPi1 and RPi2.

So... No issue with my music tracks, just PMP 1.0.1.42.

**Comment by atrus05** [comment] 2015-10-29 19:06
@NedtheNerd What @wm4 is saying is the explanation, not that it will stay like this :)
You can upload the song to a solution like dropbox or similar, and then link it in this ticket.

Additional info from Ned in the thread:

"Hardware Setup for testing (still using Rasplex for main HT)
RPi -> Sony AV Receiver -> Sony Bravia TV
Audio Settings
Device Type - HDMI
Channels - 5.1
Device - Autoselect device
Normalise Download Volume - Unchecked (Notice correct spelling of Normalise!)
Show Advanced Settings - Checked
Dolby Digital (AC3) - Checked
DTS (DCA) - Checked
Exactly the same hardware setup and Audio Settings as I had for PMP 1.0.0.5, which didn't exhibit the same problem in playing back music tracks.
I have also now tested this further by playing whole albums rather than playlists, on the same album some tracks skip with the error message, others play, some albums play the whole way through, others don't play anything. Same result whether an album of mp3's at various bitrates or m4a at 256.
Music playback yesterday with 1.0.0.5 amounted to approx 7 hours constant playback without issue.
Suffice to say all tracks play back fine on Rasplex."

**Comment by NedtheNerd** [comment] 2015-10-29 19:07
Can also confirm that same music tracks play OK on Plex for XBox 360, Amazon Fire TV stick, Plex for Windows, PlayStation 4 and Plex for Smart TV, only device I haven't got is a Roku.

Regards

**Comment by NedtheNerd** [comment] 2015-10-29 19:13
@atrus05 

I get that, just trying to provide as much info as I can to narrow down the issue, I'm from a Developer and Tester/QA background.

Regards

**Comment by mseeley** [comment] 2015-10-30 10:41
I'll look in to this in the morning to verify if fixing https://github.com/plexinc/konvergo-issues/issues/166 changed non-transcoding music playback.

@wm4 fwiw fixing transcoded music support meant plugging in the configuration for PMP to use the dummy video music transcoding approach for PMP. Dummy video serves the transcoded music as the audio stream along with a dummy video stream within a matroska container. That sounds awfully like something that would send a `video` instruction. Will look.

**Comment by wm4** [comment] 2015-10-30 11:00
@mseeley: note that while web-client sent it marked as ``video``, the actual playback URL was not transcoded. (This is probably already clear - just mentioning it to be sure.)

**Comment by NedtheNerd** [comment] 2015-10-30 12:05
Will post a file in the next hour.

Still can't understand why you have to transcode music files, especially to an .mkv container.  I know that you thought it was a way of solving your perceived problem of .m4a playback on Sony TV's (which the original release played OK).

I am happy to test any potential fixes if you PM me a link to download the file.

**Comment by NedtheNerd** [comment] 2015-10-30 14:10
@wm4 

Dropbox link for an album that will not play any track.  Note this link will be removed in 6 hours.

https://www.dropbox.com/sh/8nq1cfmiv6pm93y/AABmHmaQoSUReEYxr9sBOexwa?dl=0

**Comment by wm4** [comment] 2015-10-30 15:02
Thanks a lot, I appreciate sample files.

**Comment by mseeley** [comment] 2015-10-30 19:11
It's interesting. It is definitely related to the `type: 'video'`, sending `type: 'music'` for Ned's files causes them to play as intended.  For context my sample audio containers/codec files and an iTunes M4A all play correctly with `type: 'video'`. It's the mutant PNG + failed decoding which is causing playback to fail.

Testing the `type: 'music'` change a bit more before committing.

**Comment by mseeley** [comment] 2015-10-30 19:30
Thanks a lot for the issue report and sample files Ned. :+1:

**Closed** 2015-10-30 19:29 UTC
Labels: bug

**Comment by NedtheNerd** [comment] 2015-10-30 19:43
@mseeley 

Can you confirm that m4a files will Direct Play and not be transcoded like you have done with Sony TV app?  Still cannot understand why you want to send m4a as type: video, do you do this with all music file types, MP3, flac, etc?

Regards

**Comment by mseeley** [comment] 2015-11-02 21:28
Yes will direct play.

The Sony TV can play M4A but its eventing is broken. We get no notification that the video has started and no time updates while the video is playing. To our system it looks like the video playback has stalled mysteriously. We transcode to video because our standard transcoding to audio doesn't work on TV platforms. We can reliably transcode to video so we transcode audio to a fake/dummy video which works reliably on all platforms.

**Comment by NedtheNerd** [comment] 2015-11-03 11:44
Having done some further investigation the albums that demonstrate this behaviour had track info, album art populated by MusicBrainz Picard, have just replicated this with another album.

Regards

**Comment by NedtheNerd** [comment] 2015-11-03 17:10
After even more investigation, it happens with a brand new rip with artwork added in iTunes from a scan of the CD cover I did myself, no consistency!!!!

**Comment by wm4** [comment] 2015-11-03 17:41
Well, this means iTunes definitely is writing cover pictures not in the way the Apple mp4 documentation says it should.

**Comment by NedtheNerd** [comment] 2015-11-03 17:47
But not in previous versions, a lot of stuff I ripped a couple of years ago play OK.

As you seem to have a fix for this (assuption, because this issue is closed) I'll not spend anymore time investigating this, already spent 8 hours.  Thanks for looking at this, I did notice someone else posted a similar issue in the forums.

**Comment by NedtheNerd** [comment] 2015-11-07 11:51
Confirmed as fixed in 1.0.2.
