### ISSUE TITLE
Cannot compile on linux mint 17.3

### ISSUE THREAD

**Issue by Swashbunglar** [plexinc/plex-media-player#369] opened 2016-06-27 22:34 UTC
Any attempt to compile plex-media-player on linux mint 17.3, ninja fails to read configuration file

It fails with the following output:

   Change Dir: /home/evanblack/plex-media-player/build/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/sbin/ninja" "cmTryCompileExec2199946516"

  die: error: unable to read configuration filelog: reading configuration
  file: cmTryCompileExec2199946516

**Comment by tru** [comment] 2016-06-28 04:26
You are maybe missing ninja?

**Comment by Swashbunglar** [comment] 2016-06-28 06:47
Nope ninja-build 1.3.4-1.1ubuntu0.14.04.1 Haven't found any option for any later build either.
I've also checked permissions.. all good there.

**Comment by tru** [comment] 2016-06-28 07:03
Do you have CMakeFiles/CMakeError.txt file? What does that say?

**Comment by timinski** [comment] 2016-06-29 03:49
I have a similar issue on Lubuntu 14.04 64bit.  Have spent much time troubleshooting before finally posting here.  

"-- Configuring incomplete, errors occurred!"

Ninja-build is installed. 

CmakeError.txt has a few errors referring to maxosx (!) and also: "cannot find -lpthreads"

Is someone is interested to help, I've attached the two Cmake log files: 

[CMakeOutput.log.txt](https://github.com/plexinc/plex-media-player/files/338512/CMakeOutput.log.txt)
[CMakeError.log.txt](https://github.com/plexinc/plex-media-player/files/338513/CMakeError.log.txt)

**Comment by Swashbunglar** [comment] 2016-06-30 16:03
I gave up after 3 days. I had to do so many workarounds because the "instructions" are don't seem to be written with ubuntu/debian in mind.
I had EVERY prerequisite possible and it always failed. No matter how many times, or HOW you install/build mpv "libmpv.so.1" libraries will never be on your system.
libmpv.so.1 seems to be for fedora, as I've yet to find ANYTHING for ubuntu/debian
So it's unlikely this will ever be compiled on an ubuntu/debian system until the developers actually take time to give deb systems the love it deserves. lol
When mint is 3 times more popular than fedora and the current number one distro, you'd think you'd want to make a compatible build for it. lol
I finally just looked at third party clients in the plex forums. The top open source client is gold. Works beautifully with new server and fixes alot of the old issues of PHT.
Best part.. just a deb file, no building three separate things or hunting down requirements for all of it just to satisfy the needs of one program. lol
This will keep me happy until an actual ubuntu based build/release for PMP.

**Comment by wm4** [comment] 2016-06-30 16:30
Sorry about that experience. We planned doing official Ubuntu packages long ago, but other thing got in the way. Compilation instructions can not always account for all corner cases either. Even if you run them on distro as popular as Mint, there are always many little details that are different on each distro release (and from the base distros like Ubuntu and Debian) that can mess up the build process.

> So it's unlikely this will ever be compiled on an ubuntu/debian system

Except mine, of course.

> until the developers actually take time to give deb systems the love it deserves. lol

I can try to go through the whole process myself from a fresh Ubuntu install next week or so.

**Comment by timinski** [comment] 2016-06-30 16:46
You're a trooper!  Thanks very much for the detailed reply.

As I type this, I'm actually listening to audio playing from PMP on a
headless Lubuntu 14.04 RAID box via:

1) Setting up NoMachine for fast remote control troubleshooting from here:

https://www.nomachine.com/download

2) then installing PMP from a build I found here:

https://launchpad.net/~nicjo814/+archive/ubuntu/pmp/+packages

3) Then had to install a bunch of QT packages (despite having installed QT
already) from here:

https://launchpad.net/~beineri/+archive/ubuntu/opt-qt561-trusty/+packages

4) And lastly, had to install lbcec2 from here (despite already having a
later version of the package):

https://launchpad.net/ubuntu/trusty/amd64/libcec2/2.1.4-1ubuntu2

Seems to be working nicely.....especially when listening to Dakota Station
singing "My Funny Valentine"

:-)

-- David

P.S., As an old friend used to say of such things: "This is too much like
work!"

**Comment by timinski** [comment] 2016-06-30 16:55
@wm4 

That would be wonderful!! ("I can try to go through the whole process myself from a fresh Ubuntu install next week or so.").  

The PMP version I finally got to work is several iterations back from the latest 'n' greatest and I'll use your build to replace it.

**Comment by wm4** [comment] 2016-06-30 16:58
(By that I meant fixing the instructions in the README, not making an official build. Making an official build with involve making it work on our CI and so on - including dependencies - which simply is a major task.)

**Comment by wm4** [comment] 2016-07-07 18:35
OK, I've done that. I installed Ubuntu 16.04 on a VM, and built everything from scratch. Here's the result: https://github.com/plexinc/plex-media-player#building-on-linux

I haven't hit any particular problems, though.

**Comment by Swashbunglar** [comment] 2016-07-07 20:23
Fan-friggin-tastic wm4! I'm upgrading to 16.04 very soon, so looking forward to trying this out!

**Comment by timinski** [comment] 2016-07-07 21:05
Nicely done wm4!!

**Comment by timinski** [comment] 2016-07-07 21:22
Question that relates and/but doesn't and to which I cannot locate an answer anywhere despite much hunting:

I have the Lubuntu PMS / MediaPlayer combo setup described above streaming nicely to Android, etc Plex clients and further to a Chromecast dongle on my old-school stereo amp's AUX input, all controllable via the Plex Android, Plex iOS and related Chromecast apps.....  

......What I'd like to add is a Raspberry Pi2B & Amp+ node on my WiFi, running Rasplex (or other....maybe PMP??) all visibile as another Chromecast Audio client (target)   The Amp+ will be speaker-wired to 4ohm (or maybe 8ohm) non-powered speakers.  I'm sure I saw a HowTo somewhere but for the life of me, I cannot find my way back to the site/page for setting up the Rpi2 as a Plex/Chromecast player. 

Any ideas / clues / redirections?

**Comment by wm4** [comment] 2016-07-08 12:48
I've modified the Linux instructions further, also reproduced them to make sure they actually work the way they were written down.

@timinski I don't know, but Plex has its own non-chromecast casting abilities, not sure if that's what you're looking for.

**Comment by timinski** [comment] 2016-07-08 16:37
@wm4    Thanks again for your response(s).
Well, yes and no.  The chromecast capability allows me to easily manage multiroom groupings from a smartphone or tablet to CC dongles or any device, browser, other that supports it.  The audio CC dongles also have very nice built-in DACs.  I went in the direction of Pi2B/Amp+ combo to drive good quality analog speakers.

**Comment by tru** [comment] 2016-08-02 09:52
Since this ticket was originally about building on Fedora and that seems to have been solved I am going to close this ticket, re-open if that's wrong.

**Closed by tru** 2016-08-02 09:52 UTC
