### ISSUE TITLE
player: PMP won't start, generating large .xsessions-errors file

### ISSUE THREAD

**Issue by wamari** [plexinc/plex-media-player#743] opened 2018-05-26 20:41 UTC
### Test environment
PMS Version: N/A
PMP Version: 2.10.0.849-e02dbeca
Platform : Antergos Linux

### Steps to reproduce
1. Installed latest version of PMP, it may also be an issue with qt5.11

### Current behavior
1. PMP stuck on splash screen
2. Genrating large .xsession-errors file, in my case upto 90GB spewing the following lines
```
[17938:18165:0526/232935.585345:ERROR:gl_surface_qt.cpp(305)] eglCreatePbufferSurface failed and surfaceless context not available
[17938:18165:0526/232935.585356:ERROR:gl_surface_qt.cpp(312)] Requested OpenGL implementation is not supported. Implementation: 0
```

### Expected behavior
1. PMP should open normally

**Comment by erenfro** [comment] 2018-05-27 06:56
I am having this issue as well. Soon as you click on a user in a multi-user setup in Plex, those errors start spewing out. This only started happening after updates were installed, of which qt 5.11 was included in that from 5.10.

**Comment by wamari** [comment] 2018-05-27 07:02
Have you tried downgrading Qt 5.11? I tried but still not working...

**Comment by erenfro** [comment] 2018-05-27 21:45
I managed to get this working again by downgrading back to qt-5.10 from my package caches, and re-compiling against 5.10 again, so yes, it's some new problem spawned from 5.11 specifically.

**Comment by wamari** [comment] 2018-05-29 05:18
i also downgraded my Qt 5.11 packages to Qt 5.10 and recompiled, working great now...

**Comment by ludenticus** [comment] 2018-06-02 17:54
Why was closed this issue?

**Comment by mannp** [comment] 2018-06-05 21:51
@LongChair shouldn't this be opened until plex catches up with the latest qt builds?

**Comment by erenfro** [comment] 2018-06-05 22:59
I kinda have to agree in the sense of the actual problem, why it was reported, and the fact  that it does effect PMP now, and in the future.

**Comment by erenfro** [comment] 2018-06-16 01:17
Also, for reference. Solus issues regarding this as well:
https://dev.solus-project.com/T6542

**Comment by AndreasBackx** [comment] 2018-06-29 18:28
@LongChair any update or ETA on this? Downgrading can be a pita on Arch.

**Comment by ATRIKO** [comment] 2018-07-02 23:35
Completely unusable on my Arch Linux HTPC without qt 5.11 support.

I've canceled my Plex Pass until you have qt 5.11 support.

**Comment by mseeley** [comment] 2018-07-02 23:40
Longchair is out for a bit, bumping so we see this during triage.

**Comment by wamari** [comment] 2018-07-03 03:50
Completely unusable for now with qt 5.11 resorted to using kodi with plex add on until this is resolved.

On Jul 3, 2018 2:41 AM, Matt Seeley <notifications@github.com> wrote:

Reopened #743<https://github.com/plexinc/plex-media-player/issues/743>.

**Comment by SilverMight** [comment] 2018-07-03 23:34
Glad to see the issue was reopened. I'm also experiencing this issue on Arch, qt 5.11

**Comment by tkh23** [comment] 2018-07-07 00:56
Any update/ETA?

**Comment by mseeley** [comment] 2018-07-07 01:07
No not yet. Updating the QT dependency requires special knowledge and takes work across several teams. We're discussing how to get this done. Will update here when we have a better idea wrt timing.

**Comment by mseeley** [comment] 2018-07-10 18:04
Self-assigning for tracking.

**Comment by hak8or** [comment] 2018-07-15 02:20
In the meantime, for anyone who finds this via googling, what's the recommended way to downgrade QT on Arch to get this working? Is it only during the compilation, or is it also to run it?

**Comment by duyfken** [comment] 2018-07-15 02:58
@hak8or Install [downgrade from the AUR](https://aur.archlinux.org/packages/downgrade/) and use this command in the terminal and select the last version before QT 5.11 (QT 5.10.1 from memory):

`downgrade qt5-base qt5-declarative qt5-location qt5-quickcontrols qt5-webchannel qt5-webengine qt5-x11extras qt5-xmlpatterns qt5-script`

Then install [plex-media-player from the AUR](https://aur.archlinux.org/packages/plex-media-player/) and it should now build the latest PMP version correctly

(if it offers to add the qt5 packages above to IgnorePkg, do it. Then the qt5 packages won't be upgraded until you go back and remove them from IgnorePkg either in Pamac or /etc/pacman.conf after this issue has been fixed)

**Comment by yacn** [comment] 2018-07-25 04:08
> In the meantime, for anyone who finds this via googling, what's the recommended way to downgrade QT on Arch to get this working? Is it only during the compilation, or is it also to run it?

@hak8or easiest workaround to avoid messing with your dependencies (which can make life hell on any OS but especially Arch) is to install Kodi and use the Plex for Kodi plugin

**Comment by zevdg** [comment] 2018-07-25 04:43
Alternatively, just use https://app.plex.tv until this is fixed.

If you're running a recent build of chrome you can even "install" the plex web app by choosing "Create Shortcut" in Chrome's menu.  You might have to enable "Desktop PWAs" in chrome://flags first.

**Comment by mseeley** [comment] 2018-07-27 22:06
Unfortunately no. I spotted #681 this morning. I'm following up with folks next week to determine if we can make Linux easier for many and side step this upgrade.

**Comment by frebib** [comment] 2018-07-28 22:15
Avoiding the problem by packaging old versions of software is not a solution

**Comment by MobiusReactor** [comment] 2018-08-03 04:27
While I agree that it's not a solution, it would provide a decent workaround in the interim period until QT 5.11 support is added.

**Comment by nshtg** [comment] 2018-08-03 06:56
My `xorg-session.log` went up to 390GB until my NVMe SSD was full. Was thinking about buying a Plex Pass, but since I can't use it with Arch it's a no me.

**Comment by yacn** [comment] 2018-08-03 07:15
@zevdg that's obviously an option but it doesn't work in all cases. the draw of PMP/Kodi is that no/minimal (like audio-only) transcoding needs to take place which besides just being nice in the case of regular SD content, is very useful for higher bitrate files if you don't have the CPU power to transcode them on the fly and direct play is necessary for 4k content w/ HDR because transcoding strips out the HDR information subsequently causing the picture to look bad. 

@nshtg just use kodi w/ the plex plugin in the meantime.

**Comment by wamari** [comment] 2018-08-03 07:27
Use the plex plugin for Kodi as a temporary solution.

On 3 Aug 2018 09:56, nshtg <notifications@github.com> wrote:

My xorg-session.log went up to 390GB until my NVMe SSD was full. Was thinking about buying a Plex Pass, but since I can't use it with Arch it's a no me.

**Comment by yacn** [comment] 2018-08-10 08:00
@mseeley any eta? PMP is about to be dropped from the Solus repos fwiw.

**Comment by tkh23** [comment] 2018-08-15 18:49
Still nothing? What are you guys sucking each other's dicks over there? More and more programs can't run on ARCH due to having to keep old version of QT5. VLC won't even start into GUI now.

**Comment by mseeley** [comment] 2018-08-15 21:28
Hi @yacn, no 😢.

All, this is a tough one for us. We have a couple challenges to updating Qt:

1. Updating Qt requires us to also update our Windows build system. Qt 5.11 requires Win 64 to build a Qt Conan package.
1. We have a very small team of folks who are well versed in Jenkins, Conan, and our OS targets.

The `xorg-session.log` explosion is absurd. Needing to downgrade _system Qt_ to work around the build is also really troublesome. I've updated our documentation to call out the hard dependency on Qt 5.9.5. I apologize that this wasn't done earlier.

We officially support PMP on Windows and macOS. A Qt upgrade is on our roadmap but it's prioritized behind other work based on organizational goals.

Understanding this isn't likely anyone's wish, your best bet to build on Linux is to use a dedicated environment such as VM or Docker container. This allows for building with a Qt version that doesn't affect the overall system dependencies. Using Kodi with the Plex plugin is another alternative although also with tradeoffs.

I'm closing this issue again based on the information and available workarounds above. 

I understand that some folks will be frustrated and ask personally for their patience. I ask everyone to be civil in their comments.

**Closed by mseeley** 2018-08-15 21:28 UTC
Labels: component:host, type:bug

**Comment by AndreasBackx** [comment] 2018-08-16 11:14
@mseeley is there an issue regarding upgrading to Qt 5.11 that includes everything that needs to be done? I could give it a shot, but not for another month because of exams. Maybe I could at least do something to speed this up cause Plex is currently unusable for me on the web client. The native client is the only one that can properly handle smooth streaming of my video files it seems.

**Comment by sentriz** [comment] 2018-08-16 11:35
@AndreasBackx 
is [flatpak](https://flatpak.org/) an option?
@TingPing has a repo with PMP [(thread)](https://github.com/plexinc/plex-media-player/issues/681)
```
flatpak remote-add tingping https://dl.tingping.se/flatpak/tingping.flatpakrepo
flatpak install tingping tv.plex.PlexMediaPlayer
```

**Comment by AndreasBackx** [comment] 2018-08-16 14:09
@sentriz thank you. I'll give that a shot.

I do wonder how come PMP depends so much on Qt. Is there much more to it than a Qt Webkit Bridge?

**Comment by yacn** [comment] 2018-08-16 17:44
@sentriz bundling old dependencies is bad engineering.

**Comment by danbob** [comment] 2018-08-16 17:49
To quote an earlier reply,
> While I agree that it's not a solution, it would provide a decent workaround in the interim period until QT 5.11 support is added.

**Comment by sentriz** [comment] 2018-08-16 22:01
@yacn I didn't say it was good engineering, but it's a decent workaround given the current situation

**Comment by MobiusReactor** [comment] 2018-08-28 16:43
For those running an Arch-based distro, someone took the time to add the appropriate version of qt5 to the AUR and the AUR plexmediaplayer package now uses those as dependencies. For me, this seems to work better than the flatpak package which seemed to be running a bit slow.
Details available in the comments [here](https://aur.archlinux.org/packages/plex-media-player/).

**Comment by hak8or** [comment] 2018-08-28 16:47
I can confirm this works on arch after the changes the package maintainer
made. Thank you!

It's shocking how plex doesn't consider this a critical bug that should be
fixed immediately considering the impact it's had on so many people based
on this git issue alone.

Keep in mind it takes a very long time to compile, meaning on my system it
took over 2 hours (i5-3570k). Most of this seems to be webkit.

**Comment by vguerci** [comment] 2018-09-03 20:27
What about supporting several qt versions?
~~~
#if QT_VERSION < 0x050000
.....
#else
.....
#endif
~~~

**Comment by mseeley** [comment] 2018-09-04 20:18
Hi there everyone. I appreciate the kind feedback.

Our Qt version dependency is locked at 5.9.5 for the foreseeable future. Updating the build-time Qt dependency requires us to update supporting build infrastructure. Our team is small and the subset capable of making the infrastructure changes is smaller still. This work in on a todo list although you can imagine it's not alone.

This changed the issue from a bug to a known limitation once the correct Qt version information was included in our documentation. With this in mind I closed this issue. I don't believe an open to-do issue without a milestone is helpful.

@AndreasBackx I don't know how the Qt dependency is handled for Linux. On macOS and Windows the Qt dependency is downloaded from Conan. If it's handled the same I'm unsure what our options are. If it is somehow handled differently perhaps we have some leeway.

**Comment by AndreasBackx** [comment] 2018-09-04 21:55
@mseeley the solution we currently have on Arch (don't know about the rest) is compiling the Qt dependencies on our machine. Which thanks to [degeberg](https://aur.archlinux.org/account/degeberg) on the AUR is automatically done when installing the plex-media-player package. The problem however is that this takes around 2 hours even on my machine (which has a Ryzen 1700). My machine certainly isn't the top of the line, but it should be in the top range of PCs. If my PC takes such a long time, it might take a whole day for some laptops. Granted it's a one-time thing I assume, it makes Plex almost unusable for people with a laptop running Arch. Many people use a barebones Linux distro because they've got an old laptop so I assume a relatively high percentage of people might face this problem.

Could we just get some more information on what we can do in a PR perhaps to add support for Qt 5.11 ourselves? I've never worked with Qt myself, but I might be able to learn it or someone else might be able to pick it up.

**Comment by Libbum** [comment] 2018-09-05 00:16
"We have to upgrade our build system to provide an application you pay for, so please downgrade you build system instead" seems like a really odd way of running a business based on software.

**Comment by rphillips** [comment] 2018-09-05 04:05
Arch has the current release of QT version 5.11.1. I found an [issue](https://bugreports.qt.io/browse/QTBUG-68479) and patch for the exact OpenGL context error we are seeing being patched in QT 5.11.2. According to QT's wiki, the release of QT 5.11.2 should be sometime this week ([or so](https://wiki.qt.io/Qt_5.11_Release)). I haven't build QT 5.11.2 (or master) from version control to test this out, but once QT is updated PMP might just work.

https://bugreports.qt.io/browse/QTBUG-68479

**Comment by rphillips** [comment] 2018-09-21 14:56
Just to followup from my previous post, Arch was updated with 5.11.2 of QT. Plex Media Player (plex-media-player-git from AUR) is running smoothly for me.

**Comment by Libbum** [comment] 2018-09-21 15:17
@rphillips am I missing something here? The `-git` AUR package still has `qt5-pmp-quickcontrols`, `qt5-pmp-webengine`, and `qt5-pmp-x11extras` dependencies, so it's still building against 5.9.5 right?

**Comment by rphillips** [comment] 2018-09-21 15:32
There is a dependency on qt5-pmp-webengine, but the binary is linked against qt5-webengine (5.11.2).

**Comment by yacn** [comment] 2018-09-22 20:11
what a fucking joke of a company.

**Comment by SilverMight** [comment] 2018-09-27 19:39
Definitely works. I removed the qt5-pmp dependency and made sure it wasn't installed and it works fine

**Comment by mseeley** [comment] 2018-10-12 18:12
Thanks @rphillips. There's another indication that Qt 5.11.2, https://github.com/plexinc/plex-media-player/pull/785, is also working correctly. Has anyone else confirmed?

**Comment by truckershitch** [comment] 2018-10-12 18:31
I'm running PMP in Fedora 29 with Qt Webengine 5.11.2.  I had to install the F30 version of Qt Webengine, but the other RPMS were from F29.  I've been running it for a few weeks now.

**Comment by Kriskras99** [comment] 2018-10-13 11:13
It works for me with Qt 5.11.2 on Arch Linux

**Comment by Kriskras99** [comment] 2018-10-13 11:14
@iurab to delete the qt5-pmp packages just run this command:
`
sudo pacman -R qt5-pmp-base qt5-pmp-declarative qt5-pmp-location qt5-pmp-quickcontrols qt5-pmp-webchannel qt5-pmp-webengine qt5-pmp-x11extras qt5-pmp-xcb-private-headers qt5-pmp-xmlpatterns
`

**Comment by MobiusReactor** [comment] 2018-10-14 03:04
I can confirm it seems to be working for me now as well.

**Comment by DavidCWGA** [comment] 2018-10-16 01:50
For what it's worth, it's still broken in Fedora 29 Beta.

**Comment by mseeley** [comment] 2018-10-16 04:44
Excellent, thank you everyone whom provided feedback. 🌤🌈 

Thank you too @rphillips for locating the issues and resolution in Qt 5.11.2 and you too @Kriskras99 for the `pacman` recipe. 👍

**Comment by truckershitch** [comment] 2018-10-16 09:40
@DavidCWGA 
> For what it's worth, it's still broken in Fedora 29 Beta. (And 28, obviously.)

In Fedora 29 Beta, you can run

`sudo dnf upgrade qt5-qtwebengine --releasever=30`

and install the version from Rawhide.  When there is an F29 release of 5.11.2, you can install it instead.
