### ISSUE TITLE
Can't resume playback of a HEVC/H.265 file when using Hardware Decoding

### ISSUE THREAD

**Issue by alexandrevryghem** [plexinc/plex-media-player#960] opened 2020-04-27 00:49 UTC
### Test environment

**PMS Version: 1.19.1.2645-ccb6eb67e (installed on Windows 10 x64)**
**PMP Version: 1.8.2.1192-89432618 (on Windows 10 x64)**
**Platform: Windows 10**

### Steps to reproduce
It always happens when I try resuming a H.265 encoded video.

### Current behavior
When I try to watch an episode/movie and I select Resume from last position and the episode/movie is a H.265 file the playback never starts. When I try to close the player, put it on pause, … the plex app crashes but when I select Start from Beginning and then manually set it on the right time the playback starts.

### Expected behavior
It should just play

[error.zip](https://github.com/plexinc/plex-media-player/files/4536811/error.zip)
[Plex.log](https://github.com/plexinc/plex-media-player/files/4536813/Plex.log)
[Plex Media Server Logs_2020-04-14_20-02-45.zip](https://github.com/plexinc/plex-media-player/files/4536814/Plex.Media.Server.Logs_2020-04-14_20-02-45.zip)

**Comment by mseeley** [comment] 2020-04-28 02:16
Hi @r0747249 👋 thanks for the logs and demo video.

It appears that it could be a decoder hang:

```
2020-04-27T00:31:59.264 [ DEBUG ] mkv: seek done 
2020-04-27T00:31:59.285 [ DEBUG ] vd: Pixel formats supported by decoder: dxva2_vld d3d11va_vld d3d11 cuda yuv420p10le 
2020-04-27T00:31:59.285 [ DEBUG ] vd: Codec profile: Main 10 (0x2) 
2020-04-27T00:31:59.285 [ DEBUG ] vd: Requesting pixfmt 'dxva2_vld' from decoder.
```

Do any of these avoid the crash?

- Disable hardware decoding
- Use the [1.9 pre-release build](https://artifacts.plex.tv/plex-desktop-alpha/1.9.0.1198-0c1b003f/windows/Plex-1.9.0.1198-0c1b003f-x86_64.exe?_ga=2.5720563.1726240059.1588015881-1657052277.1583882641)

**Comment by r0747249** [comment] 2020-04-28 13:33
I don't use hardware decoding so that's not the problem and I tried resuming a HEVC video with the 1.9 pre-release build and I have the same problem. 
[logs.zip](https://github.com/plexinc/plex-media-player/files/4546052/logs.zip)

**Comment by mseeley** [comment] 2020-04-30 21:42
Hi @r0747249, we did make some changes to the player but weren't expecting a fix for this specifically.  I've added this an internal issue to validate hwdec handling.

If you're interested in investigating we could make use of a sample file: https://support.plex.tv/hc/en-us/articles/201035968-Generating-Sample-Files-from-Media that reproduces the problem. If you'd like to share the original file instead (via Google Drive or similar hosting) then you can send me a message via our forums: https://forums.plex.tv/u/mattseeley/

**Comment by r0747249** [comment] 2020-04-30 23:38
This is the sample file you requested: [black_widow.zip](https://github.com/plexinc/plex-media-player/files/4561834/black_widow.zip)

### **Steps to reproduce**
1. Play the file
2. Close the file after playback has reached 1 minute
3. Try to play the file again by clicking _Resume from x:xx_ 
4. The app doesn't respond anymore and if I click on a button the app crashes

**Comment by r0747249** [comment] 2020-06-09 09:46
Is there any update on this issue?

**Comment by chrisallen** [comment] 2020-06-15 09:30
I tried to reproduce this on my ApolloLake NUC running Windows 10 and I can resume HEVC video with and without HW decoding enabled. Could you try again using Plex Desktop 1.12?

**Comment by r0747249** [comment] 2020-06-15 14:38
I used the plex desktop app and I still can't resume the files when hardware encoding is enabled (I test it every time there is a new update so when it will be fixed I will close this thread). I tried it on different laptops and they all had the same problem :/

**Comment by r0747249** [comment] 2020-07-29 22:40
I saw that you guys updated the mpv so I tested it again but it still doesn't work 😕. Here are the <a href="https://github.com/plexinc/plex-media-player/files/4997793/Plex.log">logs</a> from when he is buffering and where he finally crashes. I also made these <a href="https://github.com/plexinc/plex-media-player/files/4997813/Plex.log">logs</a>, here I didn't click on resume playback but on start from beginning and then I manually changed the time (this doesn't crash), I hoped you could maybe compare the logs and find the bug idk 😛

**Closed** 2021-03-04 09:55 UTC

**Comment by mseeley** [comment] 2021-03-05 20:54
Apologies @alexandrevryghem that we weren't able to figure this one out. :(

**Comment by alexandrevryghem** [comment] 2021-03-05 23:02
It doesn't happen on my new laptop so it doesn't bother me that much and I told the other users on my server to disable hardware encoding

**Comment by henrikschytte** [comment] 2022-04-24 21:29
It happens on all my TV's ---- LG, Samsung and TCL android ...  and it seems to be a known problem if you search the internet ... also forward and backward is NOT working ... please fix these issues fast ... remember we pay for your software!!!
