### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [plexinc/plex-media-player#92] opened 2015-10-30 11:53 UTC
I would like to point out that identifiers like "[`__COMPONENT_MANAGER_H__`](https://github.com/plexinc/plex-media-player/blob/3d4859f1b1b7aaa3a1be31699fc9cc9295662848/src/ComponentManager.h#L1)" and "[`_DISPLAYMANAGEROSX_H_`](https://github.com/plexinc/plex-media-player/blob/53192cb022f478a438c4dfaf451c58981995ba17/src/display/osx/DisplayManagerOSX.h#L9)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by wm4** [comment] 2015-10-30 11:55
Yep, this is true. While it doesn't cause any actual problems, it definitely violates the standard. I think we'd accept a PR for this.

**Comment by tru** [comment] 2016-02-04 08:53
I will close this since we have not received a PR and it doesn't seem to be a pressing issue right now.

**Closed by tru** 2016-02-04 08:53 UTC

**Comment by elfring** [comment] 2016-02-04 09:20
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by wm4** [comment] 2016-02-04 10:06
Like someone else said, reserved identifier violation is literally the least important undefined behavior ever. We're open to fixing it, but we have enough to do at hand that 1.) we can't spend our time running search&replace for fixing issues that are almost 100% theoretical, and 2.) to argue about whether it's needed or not. If you really care, make a PR. If you can come up with an actual real world bug caused by this, we'll fix it with pleasure.
