### ISSUE TITLE
Playlists not showing up

### ISSUE THREAD

**Issue by millifoo** [plexinc/plex-media-player#21] opened 2015-10-21 14:48 UTC
Plex in browser:
<img width="1162" alt="screen shot 2015-10-20 at 5 40 49 pm" src="https://cloud.githubusercontent.com/assets/15223429/10639947/403a1bb0-77d8-11e5-8d92-16e1d5df8cb8.png">
<img width="1154" alt="screen shot 2015-10-20 at 5 40 58 pm" src="https://cloud.githubusercontent.com/assets/15223429/10639948/404ea364-77d8-11e5-9954-4c18de672e74.png">

Plex Media Player:
<img width="1920" alt="screen shot 2015-10-20 at 5 02 15 pm" src="https://cloud.githubusercontent.com/assets/15223429/10639967/50204ba8-77d8-11e5-8bfd-5c12de3b2cfd.png">

Plex Server version (as reported in the file info): 0.9.12.14
Plex Media Player version: file says 1.0.0.5-53192cb0, when it starts it says 2.4.27

Hardware: 
Model Name: 2013 MacBook Pro
Model Identifier: MacBookPro10,1
Processor Name: Intel Core i7
Processor Speed: 2.7 GHz
Number of Processors: 1
Total Number of Cores: 4
L2 Cache (per Core): 256 KB
L3 Cache: 6 MB
Memory: 16 GB
Boot ROM Version: MBP101.00EE.B09
HD: 500 GB SSD

**Comment by dogonwheels** [comment] 2015-10-21 14:49
Video playlists aren't yet supported. Music only for now, I'm afraid.

**Comment by mseeley** [comment] 2015-10-21 18:35
This is on our planned features list: https://forums.plex.tv/discussion/188207/planned-features-known-issues#latest

Closing this issue since it isn't caused by a defect in the current implementation.

Regardless thanks for the report!

**Closed by mseeley** 2015-10-21 18:35 UTC
