### ISSUE TITLE
On Deck does not advance to next episode after playing the current on deck episode

### ISSUE THREAD

**Issue by toddrob99** [plexinc/plex-media-player#263] opened 2016-03-14 19:27 UTC
On Windows 10, PMP 1.0.5, after watching an episode from On Deck (by pressing Play with the episode selected, without entering the episode details first), the same episode remains listed as On Deck. It should advance to the next unmatched episode. Navigating to another screen forces it to refresh, as a workaround.

**Comment by toddrob99** [comment] 2016-03-18 01:33
Sorry for the typo... I meant it should advance to the next unwatched episode.

**Comment by toddrob99** [comment] 2016-03-21 19:11
I haven't seen this happen since updating to 1.0.6. Closing the issue.

**Comment by toddrob99** [comment] 2016-06-06 15:12
This is still happening in PMP 1.1.1, but only within the TV section. On the main screen, it works fine.

**Comment by toddrob99** [comment] 2016-06-19 01:48
Still happening on the TV section page in PMP 1.1.2 (Win 10).

**Comment by LongChair** [comment] 2018-04-11 15:33
@toddrob99 : is that issue still relevant in last builds ?

**Comment by LongChair** [comment] 2018-04-12 04:14
@markus101 : is this something we could do ?

**Comment by markus101** [comment] 2018-04-12 17:45
Likely the same as https://github.com/plexinc/plex-media-player/issues/665

**Comment by LongChair** [comment] 2018-04-14 06:12
Agreed, duplicate of #665, @toddrob99  we'll follow that there.
Closing this.

**Closed by LongChair** 2018-04-14 06:12 UTC
Labels: component:web, type:feature
