### ISSUE TITLE
RPi - 1.0.2.89 - Selecting Show Advanced Settings

### ISSUE THREAD

**Issue by NedtheNerd** [plexinc/plex-media-player#141] opened 2015-11-10 16:49 UTC
When selecting 'Show Advanced Settings' in 'Settings', 'Audio' it blanks all settings.

This was reported as an issue in the forums in the 1.0.2RC and was to be fixed in the this release, it isn't, issue still exists.

**Comment by dogonwheels** [comment] 2015-11-10 17:42
Duplicate of the (forgotten. sorry!) #137 - thanks for the poke.

**Closed by dogonwheels** 2015-11-10 17:42 UTC
Labels: bug

**Comment by NedtheNerd** [comment] 2015-11-11 09:43
Sorry, missed that one.
