### ISSUE TITLE
Cannot play media from local server without internet

### ISSUE THREAD

**Issue by miigotu** [plexinc/plex-media-player#504] opened 2017-01-18 17:32 UTC
My internet went out today for a few hours. After entering the local server info I was able to browse the library on my Pi3, but could not play media (red box, error playing this file)
Playing with the web player on the same network had no issue

**Comment by bouscram** [comment] 2017-02-19 10:18
it look like the issue #466 I have opened... PMP is not able to play files when the server in not authenticated.

**Comment by LongChair** [comment] 2018-04-11 05:13
@markus101 : i'm not sure if this is a real issue or by design. could you confirm please ? :)

**Comment by LongChair** [comment] 2018-04-11 05:36
related to https://github.com/plexinc/plex-media-player/issues/466

**Comment by LongChair** [comment] 2018-04-12 04:25
We haven't been able to reproduce that in latest versions.
This referes probably to tv1 which won't get any fix.
We're hoping to release tv2 for embedded in a near future when all the internal testing has been completed
We're closing this. Please check with latest versions when available.

**Closed by LongChair** 2018-04-12 04:25 UTC
Labels: stat:need-feedback
