### ISSUE TITLE
Raspberry pi 2 freezes up when trying to seek or resume a video from a certain point

### ISSUE THREAD

**Issue by JayyyR** [plexinc/plex-media-player#215] opened 2016-01-22 13:49 UTC
I have PMP embedded on my Rpi 2 and when I resume a video from a certain point or jump ahead/back, it almost always buffers endlessly until it craps out. This seems to happen more on high bitrate content. It almost always happens on direct play, sometimes happens on transcoding. If I set the bitrate limit to 4 mbps, I don't see the issue.

Here is my original post on the forums: https://forums.plex.tv/discussion/203928/raspberry-pi-2-cant-direct-play-anything#latest

Here are two movies I'm seeing the issue on:

http://pastebin.com/fCtnPkCq

http://pastebin.com/hsDqzTQD

Here are logs from right after I hit play and see the issue:

http://pastebin.com/f0QmYuHF

You can see at the end there it just continues to buffer. This issue seems to be related to seeking because it happens when I try to skip ahead/back or resume in the middle. I will also say that all this content plays fine on rasplex.

**Comment by wm4** [comment] 2016-01-23 13:49
The resume case might be different, I'll have to test that. So far I wasn't able to reproduce these seeking problems, although I'm sure they do exist. Will do some more debugging next week.

**Comment by JayyyR** [comment] 2016-01-23 17:40
Thanks, let me know if there's anything I can do to help

**Comment by JayyyR** [comment] 2016-01-25 04:50
Just some more info I've found. It seems the resume problem is only happening on direct play videos.

The seeking problem happens for any jump on direct play videos. But also happens even when I'm transcoding if I skip forward a lot at once (press the 30 second skip 5 times).

So on direct play, skipping around any amount freezes the video. And on transcoding, if I skip a lot at once, it also freezes.

Not sure if this helps at all, but figured I'd add to what I found.

**Comment by LaserLock** [comment] 2016-01-25 07:58
:+1: have the same issue with series

**Comment by wm4** [comment] 2016-01-25 15:57
Still can't reproduce (used 1.0.4 RC/ninja). Something must be wrong here if I can't reproduce, yet you and some other users get the issue all the time?

**Comment by JayyyR** [comment] 2016-01-29 16:17
I have just been testing on the release version on the downloads page so: Version 1.0.3.132-16fa0ecc

When you say 1.0.4, is that a different version?

**Comment by wm4** [comment] 2016-01-29 16:35
Yeah, a pre-release version. There was a public RC a while ago. And here's a relatively recent build: https://nightlies.plex.tv/public-test/plexmediaplayer/embedded-testing/1.0.4.180-8316624d/
(Use on your own risk, and it won't auto-update.)

**Comment by wm4** [comment] 2016-01-29 16:36
PS: I also did something to this build that should generally help with video glitchiness (such as freezes), but since I couldn't reproduce your problem, I'm not sure if it solves it.

**Comment by JayyyR** [comment] 2016-01-29 18:13
Thanks, I'll test it when I get home

**Comment by JayyyR** [comment] 2016-01-30 07:24
unfortunately the same issues exist in that build

**Comment by wm4** [comment] 2016-01-30 13:04
Thanks for testing. That's unfortunate indeed. To get a real chance at fixing it I'll need a way to reproduce it.

**Comment by JayyyR** [comment] 2016-02-09 16:34
I realize this issue may not be top priority, but would it be feasible to give you a file I'm seeing this issue on? It would just be a blue screen or static avi pretty much.

Thanks for responding so quickly to these posts.

**Comment by wm4** [comment] 2016-02-09 16:54
Yes, that could help.

**Comment by JayyyR** [comment] 2016-02-12 06:09
Ok add another thing to the list of oddities. I created a blue screen AVI file to give to you but I'm not seeing the same issues as I'm seeing with the other AVI files/my blu ray MKVs. I did see problems with skipping but once but not like other movies (where it happens every time)

And resuming the video from the middle worked fine on this blue screen test unlike the other files. So I'm not sure it would do much good sending you that file

**Comment by james-west** [comment] 2016-02-15 06:50
I am having this problem as well, but I found that it only occurs for me when DTS pass-through is enabled.  If I have DTS pass-through enabled, half the time I seek while playing a file with DTS audio, playback will stop.  If I seek again quickly, sometimes playback will resume, but if I leave it for a few seconds, the three-dot buffering indicator will appear.  Once the buffering indicator appears, nothing will allow me to resume playback except restarting from the beginning, not even backing out and resuming from the same position.  When the video stops playing after a seek, my receiver indicates it is receiving stereo PCM instead of DTS.  If I disable DTS pass-through, everything starts working again, and I'm even able to resume from the point where the video froze.  The problem only occurs with DTS and not with AC3 pass-through.

Pausing sometimes causes playback to stop on files without DTS as well, but pausing and then playing will cause it to resume.  This happens only sporadically though.

**Comment by JayyyR** [comment] 2016-02-15 07:22
sorry for the dumb question but where is the option to disable/enable DTS pass-through? Not seeing it in audio settings

**Comment by james-west** [comment] 2016-02-15 07:26
You have to check "Show Advanced Settings" in the Audio section of Settings.  Pass-through is disabled by default.

**Comment by JayyyR** [comment] 2016-02-15 07:27
oddly "show advanced settings" doesn't show any additional settings for me, but I guess if it's disabled by default than its not the problem I'm having. But perhaps this is all related to an audio issue

**Comment by LongChair** [comment] 2018-04-10 15:52
Should be fixed now.

**Closed by LongChair** 2018-04-10 15:52 UTC
