### ISSUE TITLE
Full screen toggle busted

### ISSUE THREAD

**Issue by pooploser** [plexinc/plex-media-player#294] opened 2016-03-31 20:00 UTC
The full screen appears inverted: deactivated when in full screen. 
Toggling it causes some serious issues - it starts an infinite loop where it keeps going on and off repeatedly and also jumping in and out of full screen...
Only using the keyboard full screen combination made the loop stop again.

**Comment by OttoKerner** [comment] 2016-03-31 20:29
You should add the exact PMP version and build number.
Also whether you issue the fullscreen command with a remote control (and maybe a custom keymap) or a mouse.

I can't reproduce on Windows with version 1.1.0.build 260. 
Both mouse or the keyboard shortcut behave normally. I can't test with an IR remote control though.

**Comment by pooploser** [comment] 2016-04-02 14:53
This issue didn't occur again after a restart. it was build 258… will observe further and report more/close if necessary.

**Comment by bkim** [comment] 2016-05-10 09:31
PMP 1.1.1 broke all sorts of full screen toggling on OS X. Command-F brings up the "find" screen now and "\" works inconsistently (sometimes it toggles fullscreen, sometimes it does nothing). Previous versions of PMP saved the non-fullscreen window size. PMP now seems to either go full screen or to a maximized window on launch.

This is what the PMP log shows when I hit "\" and nothing happens:
```
2016-05-10 04:23:16 [ DEBUG ] InputComponent.cpp @ 149 - Input received: source: "Keyboard" keycode: "\\" : InputBase::InputkeyState(KeyDown) 
2016-05-10 04:23:16 [ DEBUG ] InputComponent.cpp @ 218 - Emit input action: ("host:fullscreen") 
2016-05-10 04:23:16 [ DEBUG ] InputComponent.cpp @ 115 - Got host command: "fullscreen" arguments: "" 
2016-05-10 04:23:16 [ DEBUG ] InputComponent.cpp @ 128 - Invoking slot toggleFullscreen 
2016-05-10 04:23:16 [ DEBUG ] KonvergoWindow.cpp @ 210 - setting fullscreen =  true 
2016-05-10 04:23:16 [ DEBUG ] InputComponent.cpp @ 149 - Input received: source: "Keyboard" keycode: "\\" : InputBase::InputkeyState(KeyUp) 
```

**Comment by tru** [comment] 2016-05-10 18:00
Cmd+Shift+F should work on OSX.

**Comment by bkim** [comment] 2016-05-11 04:03
> Cmd+Shift+F should work on OSX.

This gets it out of full screen, but it doesn't appear to put it into full screen mode.

**Comment by LongChair** [comment] 2018-04-17 16:38
@pooploser : i suppsoe we can close this now ? :)

**Comment by atrus05** [comment] 2018-04-17 17:38
@LongChair No. I can reproduce what bkim is saying when using build 2.8.0.813. Hitting Cmd-Shift-F takes it out of fullscreen, but the same command does not get me back into fullscreen.

**Comment by atrus05** [comment] 2018-04-17 17:41
If I however close down PMP, and the run the command, it will switch to fullscreen. So it seems to be another weird one :)

**Comment by LongChair** [comment] 2018-05-13 06:03
Will close this one as the original issue seems fixed.

**Closed by LongChair** 2018-05-13 06:03 UTC
Labels: component:host, type:bug

**Comment by atrus05** [comment] 2018-08-29 22:43
Oops, for some reason I missed your mention Longchair. But yeah, it has been fixed now.
