### ISSUE TITLE
PMP is always minimized upon return from Win7 screensaver

### ISSUE THREAD

**Issue by tachtevrenidis** [plexinc/plex-media-player#381] opened 2016-07-11 21:34 UTC
I have PMP in full screen mode working great. I go to sleep and the Win7 screensaver takes over after a while. When I wake up in the morning, I turn on the TV, I see the screensaver on, I press a button on the remote to dismiss the screensaver and what I see is the Windows desktop with PMP minimized (there are no other apps running). I know I can disable the screensaver as a workaround but it seems like when I return from screensaver I should be right back when I was (this is the behavior of WMC shell as well).

**Comment by wm4** [comment] 2016-07-12 13:00
In fullscreen mode, PMP disables the OS screensaver, and enables its own Plex screensaver instead. So this is probably not caused by the screensaver, but possibly due to switching off the TV. Can you test whether that is the case? Just leave everything on and let the screensaver kick in.

Also can you check whether the `minimizeOnDefocus` option is set in the PMP config file? If it is, disable it.

**Comment by tru** [comment] 2016-08-02 09:46
@tachtevrenidis did setting `minimizeOnDefocus` option help?

**Comment by Enigma0** [comment] 2016-10-05 20:09
I actually get my OS screensaver coming in and taking over despite having the Plex screensaver enabled. This is in Windows 10.

`"minimizeOnDefocus": false,
"preventSystemScreensaver": false,` - default value

Seems like maybe `minimizeOnDefocus` isn't working properly?

**Comment by LongChair** [comment] 2018-04-11 06:06
@tachtevrenidis : is this still an issue with recent builds or can we close this ?

**Comment by LongChair** [comment] 2018-04-15 07:15
@Enigma0 : pinging you then to see if this is still an issue with latest builds :)

**Comment by Enigma0** [comment] 2018-04-15 17:02
I don't use it on any windows system anymore - can't comment.

**Comment by LongChair** [comment] 2018-04-15 17:24
Ok will close this due to the lack of feedback by the OP then :)

**Closed by LongChair** 2018-04-15 17:24 UTC
Labels: stat:need-feedback
