### ISSUE TITLE
Plex Media Player on OS X does not play any videos

### ISSUE THREAD

**Issue by needo37** [plexinc/plex-media-player#6] opened 2015-10-20 20:47 UTC
Steps to reproduce:

1. Open up Plex Media Player
2. Click on User
3. Click on any video from a local server using the latest PMS
4. Wait...
5. Receive error: Video took too long to start playing.

logfile available but github will not let me  attach one.

Thank you!

**Comment by wm4** [comment] 2015-10-20 20:47
>logfile available but github will not let me attach one.

You can use this: https://gist.github.com/

**Comment by needo37** [comment] 2015-10-20 20:48
Here you go!

https://gist.github.com/needo37/f77678c6c6062a1e58b6

**Comment by tru** [comment] 2015-10-21 07:15
Do you use a USB audio card?

**Comment by wm4** [comment] 2015-10-21 10:27
>Do you use a USB audio card?

Going by the log: yes.

**Comment by tru** [comment] 2015-10-21 12:29
We are guessing that this is a dupe of #2 - If you don't use a USB audio device please reopen this issue.

**Closed by tru** 2015-10-21 12:29 UTC
