### ISSUE TITLE
PMP above v.2.15.0.882-8b488458 does not accept Shuffle Command

### ISSUE THREAD

**Issue by docsnyder12345** [plexinc/plex-media-player#797] opened 2018-11-04 09:57 UTC
### Test environment
**PMS Version:** 1.13.9.5456
**PMP Version:** above 2.15.0.882-8b488458
**Platform (Windows/OSX/Embedded):** Windows 10

### Steps to reproduce
1. Connect Plex for Android with the PMP Instance
2. Select a Playlist or a TV Series
3. Play the selected Item via "Shuffle" Command from Plex for Android

### Current behavior

1. A random Item starts playing, the Shuffle Option is not activated

### Expected behavior

1. A random Item starts playing, with the Shuffle Option for the Set activated

**Comment by mseeley** [comment] 2018-11-26 22:00
Thank you @docsnyder12345, I've tagged in our Desktop team to take a look. I need their expertise to help triage our representation of shuffle state between a controller and player. @duncanbeevers you have context on this?

Also, just double-checking that 2.15.0.882-8b488458 works correctly and it's broken in later versions.

Thanks!

**Comment by mseeley** [comment] 2018-11-29 05:08
This working correctly for me on PlexMediaPlayer-2.22.1.917-2a5a2e01-macosx-x86_64 and Plex for Android 7.7.2.7701 (eb613d3g).

When starting shuffled playback on PMP from Android I see the shuffle button active:

![screen shot 2018-11-28 at 7 03 59 pm](https://user-images.githubusercontent.com/30019/49200391-a6669f80-f340-11e8-9d06-19e2f0650501.png)

When this episode finished another episode began playing. Shuffled episode progression was 7, 6, 2.

Then when starting a specific episode, without shuffle play, the control is no longer active:

![screen shot 2018-11-28 at 7 04 18 pm](https://user-images.githubusercontent.com/30019/49200417-be3e2380-f340-11e8-9c56-136a3bc3abf3.png)

**Comment by OttoKerner** [comment] 2018-11-29 11:14
I don't think the issue is fixed.
Connect the Android mobile app to PMP.
Cast a mixed music playlist (different artists and albums) to PMP.
Result: the first track of the playlist is played and then playback stops.

**Comment by mseeley** [comment] 2018-11-29 18:43
@OttoKerner thanks for the heads up. I did test the episode case but did not test the playlist case. Please remember to include application version numbers when reporting issues or comparing behaviors.

**Comment by mseeley** [comment] 2018-11-29 21:04
- Connected Plex for Android 7.7.2.7701 (eb613d3g) to PlexMediaPlayer-2.22.1.917-2a5a2e01-macosx-x86_64
- Cast a shuffle played mixed music playlist (different artists and albums) to PMP.
- PMP first played track 4. When this item finished playback track 13 was played.
- The shuffle OSC control was selected (displayed gray background) during playback

I tested on the lastest macOS PMS: 1.14.0.5470-9d51fdfaa and a pre-release build: 1.15.0.0-35d908777.

@OttoKerner the behavior you're describing sounds like https://github.com/plexinc/plex-web-client/issues/11909. If you can reproduce please first make sure your Plex apps are up to date. Then please feel free to reopen with steps to reproduce and app versions. It's not unusual for bugs to hide, we just need more info to smoke them out.

**Comment by OttoKerner** [comment] 2018-11-29 21:11
My versions were: 
Android mobile 7.8.0.8095 (beta)
PMP 2.22.1.917-2a5a2e01on Windows 10

**Comment by OttoKerner** [comment] 2018-11-29 21:16
My versions were: 
Android mobile 7.8.0.8095 (beta)
PMP 2.22.1.917-2a5a2e01on Windows 10
My playlists are usually very big. The ones I tested with had minimum 24 hours playtime and hundreds to thousands of tracks, Most of them are smart playlists.

**Comment by OttoKerner** [comment] 2018-11-29 22:22
I just repeated testing with PMP 2.23.0.920-5bc1a2e5
Android mobile 7.8.0.8095 (beta)
Issue still exists, even with a relatively small playlist of just 16 tracks, all the same album artist (but different albums).

**Comment by markus101** [comment] 2019-03-18 20:23
This appears to be the same underlying issue as https://github.com/plexinc/plex-media-player/issues/821

That fix will be in the next release.

**Closed by markus101** 2019-03-18 20:23 UTC
