### ISSUE TITLE
Mac OS app - Minimized Player doesn't show video while playing

### ISSUE THREAD

**Issue by MrFent** [plexinc/plex-media-player#786] opened 2018-10-18 04:38 UTC
### Test environment
**PMS Version:** - 1.13.8.5395-10d48da0d
**PMP Version:** - 3.71.1
**Platform (Windows/OSX/Embedded):** Mac OS 10.14 (18A391)

### Steps to reproduce
1. Minimize the player, so that it shrinks to the bottom left corner (and you can still browse through your library.
2. Hit Play 

### Current behavior

1. The video will start playing sound, but all you see is a still picture/thumbnail on the bottom left.

### Expected behavior

1. You should be seeing the video playing.

Note: This issue only occures on the standalone Mac app. (I haven't tested the windows version) It does not occur in the (chrome) browser version.

**Comment by mseeley** [comment] 2018-10-22 21:36
Hi @MrFent thanks for filing. This definitely doesn't work as the user expects although it is working as designed.

The browser version of the app displays video stacked amongst other UI controls. Whereas PMP plays video on a layer behind all other UI controls. The browser version is using the web browser as a video player whereas PMP uses MPV as the video player. This difference in stacking order prevents the video from displaying in a mini player in PMP.

I'm closing this fella out since it's working as intended and we don't have plans to refactor video handling in PMP to support the mini player.

**Closed by mseeley** 2018-10-22 21:36 UTC
