### ISSUE TITLE
RPi2: Plex media player restarts itself when trying to playback MPG files

### ISSUE THREAD

**Issue by LeiFaWing** [plexinc/plex-media-player#220] opened 2016-02-03 19:00 UTC
**Device:** RPi2 (OpenELEC: 6.0)
**Plex Build:** 2.5.3
**PMP Build:** 1.0.4

**Steps to Reproduce:**
1. Navigate to MPG video file
2. Play MPG video file

**Current Results:**
Plex media player restarts itself when attempting to play an MPG video file.

**Comment by wm4** [comment] 2016-02-03 19:11
Sample, please.

**Comment by LeiFaWing** [comment] 2016-02-03 19:21
Video files:
mpg_720x480_7704kbps_mpeg2_8bit_29.970fps_ac3-6ch_[4ab1e96854].mpg
mpg_1920x1080_30.9mbps_mpeg2_8bit_30.000fps_mp2-2ch_[60a750c1cd].mpg 
mpg_720x480_10.4mbps_mpeg2_8bit_29.970fps_mp2-2ch_[77f36462a0].mpg 

In case if you don't have access to QA-LIN-HQ-SJC server, here is a sample mpg file:
[file.zip](https://github.com/plexinc/plex-media-player/files/116247/file.zip)

**Comment by marctwo** [comment] 2016-02-04 15:09
I confirm this behaviour when playing mpeg2 files.

**Comment by wm4** [comment] 2016-02-04 19:12
I can't reproduce a crash. I have no doubt your crashes are real of course - if possible, fish out the crash UUIDs from pmphelper.log and provide them here.

There's a new test build too: https://nightlies.plex.tv/public-test/plexmediaplayer/embedded-testing/1.0.4.187-da1dda84/

**Comment by marctwo** [comment] 2016-02-05 15:13
2016-02-05 14:21:56 [ INFO  ] CrashUploader.cpp @ 133 - Submitted crash report with uuid: "6ee84fc2-8fd0-fb53-76222a8d-1b2a460f"

No such issues on the OSX version, just Embedded on RPi2.

**Comment by wm4** [comment] 2016-02-05 17:52
So after staring at the code for a while, I actually noticed something that could have triggered this on the RPI. It only happens if you don't have a mpeg-2/vc-1 license. Please try this build: https://nightlies.plex.tv/public-test/plexmediaplayer/embedded-testing/1.0.4.188-da1dda84/

**Comment by wm4** [comment] 2016-02-05 17:52
PS: this is also a case that should have transcoded instead of direct-playing. But that is another bug.

**Comment by wm4** [comment] 2016-02-05 18:13
Currently we have a bug in our transcode logic. This causes PMP not to transcode "unsupported" codecs like mpeg2. If you don't have a mpeg2 license, the video will be decoded on the CPU, which is usually too slow (and also triggered this crash bug apparently). If you have a license, it should play fine.

We're working on fixing the transcode profile, and we'll also check for the codec licenses properly. Then this mess should finally end.

**Comment by marctwo** [comment] 2016-02-05 18:15
I'll install the licieneces and test. Is it the same procedure as OpenElec?

**Comment by wm4** [comment] 2016-02-05 18:26
Yes.

It would be nice if you could test the crashing case before installing the licenses.

**Comment by marctwo** [comment] 2016-02-05 18:29
Ok

**Comment by chrissearle** [comment] 2016-02-13 13:59
I have this repeatably on all that I've tested marked MPEG2VIDEO and VC1 - H264 on the other hand plays fine. So it's def specific to which codec's are being used.

**Comment by LongChair** [comment] 2018-04-11 15:43
@LeiFaWing : is this still relevant in recent builds ? or can we close this ?

**Comment by LongChair** [comment] 2018-04-17 15:09
Closing due to the lack of feedback, feel free to reopen if needed.

**Closed by LongChair** 2018-04-17 15:09 UTC
Labels: stat:need-feedback, type:bug

**Comment by LeiFaWing** [comment] 2018-04-18 03:02
Tested again with a RPi3 using PMP `1.3.11.758`. Not able to reproduce this issue anymore.
