### ISSUE TITLE
force all client to use the /poll API instead of the /subscribe API 

### ISSUE THREAD

**Issue by victor-perez** [plexinc/plex-media-player#640] opened 2017-12-05 07:49 UTC
Is there any option to disable the `/subscribe` API in the PMP and force clients to use the `/poll` API, I'm asking this because the `/subscribe` API is a firewall nightmare the way it works it doesn't allow to put the PMP inside isolate network without opening all ports, because with the `/subscribe` the client can pick any port.

My setup currently is:
* PMP ( Raspberry PI 3 ) inside isolated network VLAN x
* Android Plex app inside network VLAN y
* PMS ( linux ) inside VLAN z

PMP can talk directly to PMS no problems there.
Android Plex app can see the PMP and PMS also no problem there.
And the Android Plex app can start playback on the PMP without any  problems but after it started it doesn't get any updates anymore because the PMP can't talk directly to Android Plex app on some random port. This problem can easy solved if can tell the client that he need to use the `/poll` API instead of the `/subscribe` API

**Comment by LongChair** [comment] 2018-04-15 08:41
@markus101 : is there anything that can be done here ?

**Comment by LongChair** [comment] 2018-04-17 18:36
Related to https://github.com/plexinc/plex-web-client/issues/4429

**Comment by LongChair** [comment] 2018-04-17 18:38
Duplicate of https://github.com/plexinc/plex-media-player/issues/199 . Closing

**Closed by LongChair** 2018-04-17 18:38 UTC
Labels: component:web
