### ISSUE TITLE
Lengthy delay before a file begins playing when "Allow Display Mode Switching" is enabled on Mac

### ISSUE THREAD

**Issue by uncleungie** [plexinc/plex-media-player#414] opened 2016-09-08 01:14 UTC
I have enabled "Allow Display Mode Switching" in Plex Media Player on my Mac.

When selecting a video to play, there is usually a 10 second delay before the display switches refresh rate and begins to play any video file. I can replicate this behavior on two separate Mac minis running 10.11.6.

Occasionally, display mode switching works properly and the video will begin immediately. The vast majority of the time, however, a long delay is present.

I have enabled "Allow Display Mode Switching" on a Windows machine, and this bug is not present.

**Comment by uncleungie** [comment] 2016-09-08 01:44
Upon further testing, it seems that moving the mouse during the delay will immediately switch the refresh rate and begin the movie. The delay still occurs if I don't move the mouse.

**Comment by atrus05** [comment] 2016-09-08 07:30
@uncleungie Please add the PMP log from when this is happening as this is not something I can see on my Mac Mini.

**Comment by uncleungie** [comment] 2016-09-08 23:05
@atrus05 I've attached two log files, one showing a 7 second delay after starting playback, and the other with no delay. I was able to bypass the delay by moving my mouse.

It looks like the first log shows a file being selected for playback at 18:10:03. Plex Media Player detects the correct refresh rate at that same timestamp, and then nothing else is logged until 18:10:10.

The second file shows a file selected for playback at 18:32:39, and the log continues the next second at 18:32:40.

I wonder if other mac setups are experiencing a shorter delay than mine - perhaps only a second or two? Is a smaller delay present in your log file?

Thank you for looking into this!

[Plex Media Player - Delay.txt](https://github.com/plexinc/plex-media-player/files/462843/Plex.Media.Player.-.Delay.txt)
[Plex Media Player - No delay.txt](https://github.com/plexinc/plex-media-player/files/462844/Plex.Media.Player.-.No.delay.txt)

**Comment by atrus05** [comment] 2016-09-12 11:21
Thanks for the logs. Yeah there is a huge 7 second gap there which I can't explain. The only guess I have is that PMS were performing an analysis of the file during that timeframe. But to see if that was the case we would need the PMS log from the same timeframe. If you can't produce that I think you need to reproduce it again and then this time upload the PMP and PMS log.

**Comment by LongChair** [comment] 2018-04-15 07:16
@uncleungie : is that still an issue with recent PMP / PMS builds ? or can we close this ?

**Comment by LongChair** [comment] 2018-04-22 06:02
Closing this due to the lack of feedback, feel free to reopen if needed.

**Closed by LongChair** 2018-04-22 06:02 UTC
Labels: stat:need-feedback
