### ISSUE TITLE
PMP @ChromeBox - wrong picture mode 60Hz instead 50Hz

### ISSUE THREAD

**Issue by Massaguana** [plexinc/plex-media-player#208] opened 2016-01-17 16:15 UTC
Hello PMP Team,

here are an issue with PMP "Embedded Intel 64-Bit" 1.0.3 runs @ my Asus ChromeBox.

Problem there are no Picture Available because there are the wrong heard rate in there, i need 50Hz not 60Hz. I´am in Europe, we use 50Hz.

When i plug the ChromeBox to an Computer Monitor there are no Problems. Here i searching for an Setting to set 50Hz for deafult. There is nothing. But i find the Button "Allow Displaymode switching" under Setings >> Video.

Back to my TV, there are no Picture after Startup. But when i navigate blind to an Movie an Start it, tataa there are an Picture... My Movies are all with 50Hz  or 24p... both works...

What can i do?

**Comment by wm4** [comment] 2016-01-18 12:14
This must be something that goes wrong before PMP even starts (because PMP doesn't normally switch display modes on start). Do you see the splash screen? What exactly makes you think the issue is a 50 vs. 60 Hz problem, and not something else?

@ziggimon @LongChair does OE switch the mode at some point during boot?

Also, just to be sure, can we get a pmp log?

**Comment by ziggimon** [comment] 2016-01-18 12:58
Supplying /var/log/Xorg.0.log would for sure tell us what Xorg detects and what resolution it starts with.

**Comment by Massaguana** [comment] 2016-01-18 13:42
wm4: 

- No, i can´t see the splash screen. No Picture.
 
- I think this is an issue with 50 Hz vs. 60Hz because OpenELEC are with the same issue. But here i can change the Settings. 
When i Install OpenELEC new i must do this with an PC screen, here i can see something. Here i set up 50 Hz an shut down. Move the ChromeBox to my TV an Startup. Now i can see something and setup all other things.
With PMP is this not possible.

PMP on Pi2 runs out of the box fine... no Problems to take an picture on TV. May by an HDMI handshake problem.

 In moment there are runs Kodi on my ChromeBox. I can test PMP again next weekend, than with logs.

**Comment by Massaguana** [comment] 2016-01-19 16:36
ziggimon: i can´t find this folder sorry.. how does it work to see them with ssh?

Here are an clean log from Startuo PMP with connection to my AVR an TV behind. No Picture to see..
http://pastebin.com/d1xbgdE7

**Comment by wm4** [comment] 2016-01-19 18:12
>2016-01-19 16:32:26 [ INFO  ] DisplayManager.cpp @ 29 - "Mode  0:  1920 x 1080 x  0bpp @59.9339Hz" 

The log indicates that 60hz is supported.

>how does it work to see them with ssh?

Well, it's a unix path... you should be able to access it with ssh.

**Comment by Massaguana** [comment] 2016-01-20 09:10
My by the AVR supports 60hz, but my TV show´s no picture... still black screen. Is it possible to change this in can config file oder something like that?

I use an SSH Browser to look for this path... her shows all, also hidden files etc. But there are no unix folders.

**Comment by Massaguana** [comment] 2016-01-20 18:54
Okay, here are the xorg.0.log
http://pastebin.com/wyRh4iKp

**Comment by Massaguana** [comment] 2016-01-20 19:09
Very Strange. When i Startup the ChromeBox when TV and AVR are Off and Turn TV/ AVR after Startup On i have an Picture... okay it to big(Overscan) but its there.. Here are fresh clean logs with this proceed:
PMP log: http://pastebin.com/90iZe7v7
xorg.0.log: http://pastebin.com/VmNpCLMp

**Comment by Massaguana** [comment] 2016-02-03 16:32
same with 1.0.4 and new are Overscan with PMP@ RPI2 too... Now there are no non PC Client working...

**Comment by Massaguana** [comment] 2016-02-09 12:47
any change to add this feature? Or can i delete PMP?

**Comment by ziggimon** [comment] 2016-02-09 12:57
Since your hardware, RPi2 + Reciever + TV or the combinations of those are telling the RPi2 that its best match is 60Hz thats what gets selected (From logs: [1617743.473] (II) intel(0): switch to mode 1920x1080@60.0 on HDMI1 using pipe 0, position (0, 0), rotation normal, reflection none)

What you can do is place a custom xorg.conf file in /storage/.config and simply remove the 60Hz option:

http://wiki.openelec.tv/index.php/Configuring_a_Custom_xorg.conf#tab=Intel

You might need to adjust the screen to be HDMI1 and not HDMI2, but that should allow you to override the current autodetection of 60hz. Also if your running it via a reciever it should be possible for that to convert from 60 -> 50hz also.

I'm also a little stumped as why your TV wouldn't support 60hz, my TV is from 2008 and even that has 60Hz support.

**Comment by Massaguana** [comment] 2016-02-09 13:01
I test it... but i think this don´t help to calibrate the overscan...

**Comment by ziggimon** [comment] 2016-02-09 13:03
No, but it should give you a picture instead of a black screen. Have you tried setting your TV to PC mode on the HDMI input you are using for the Chromebox? That might eradicate the need for overscan.

**Comment by Massaguana** [comment] 2016-02-09 13:36
With PC mode there are massiv overscan too... and i can´t see the AVR Menue... 
Feedback from Manufacturer of TV: The TV can´t communicate over HDMI, when there are Information´s there are wrong. I must Setup The Player. with your OE PHT no Problem...

**Comment by Massaguana** [comment] 2016-02-09 13:56
hmm, i can´t find this 60hz option... don´t understand this xorg file... Is it possible to extract the correct information from another working client an put it to pmp?

**Comment by ziggimon** [comment] 2016-02-09 13:59
No.

Just remove the lines:

```Modeline    "1920x1080@59.94p" 148.352 1920 1960 2016 2200 1080 1082 1088 1125 +hsync +vsync
Modeline    "1920x1080@60p"    148.500 1920 2008 2056 2200 1080 1084 1089 1125 +hsync +vsync
```

and change:

```
Modes     "1920x1080@59.94p" "1920x1080@24p" "1920x1080@60p"
```

To

```
Modes     "1920x1080@24p" "1920x1080@50p"
```

And you may need to change HDMI2 -> HDMI1

This is how one normally overrides xorg configs.

**Comment by Massaguana** [comment] 2016-02-09 14:14
Sorry, i am blind... can´t fin this lines in my xorg.log...

**Comment by ziggimon** [comment] 2016-02-09 14:17
I think you should go to the guide I posted earlier and use the manual config method to create  your own `xorg.conf` not `xorg.log`, log files are for outputting results, the config file is for controlling the behaviour of the Xorg server.

**Comment by Massaguana** [comment] 2016-02-09 14:28
Hmm, this my xorg.conf: http://pastebin.com/1VpdKNdm
and the log: http://pastebin.com/YqCb83Hc

no picture...

**Comment by ziggimon** [comment] 2016-02-09 14:32
Why are you using the Nvidia config? Your Chromebox has an Intel GPU.

**Comment by Massaguana** [comment] 2016-02-09 14:41
i find many xorg files with nvidia in there... Okay here are an test with intel:
xorg.conf: http://pastebin.com/Vgd0wZnL
xorg.log: http://pastebin.com/zyj8P6CM

Now i have an Picture... Juhu... but with Oversacan and the picture are jumping all the time... vertikal jumping for 2 cm

**Comment by ziggimon** [comment] 2016-02-09 14:48
There are a few ways one can tweak overscan on linux with xorg. Google reviled a few results after a quick search.

```
xrandr --output HDMI-1 --set underscan on
xrandr --output HDMI-1 --set "underscan hborder" 40 --set "underscan vborder" 25
```
Ofc those values can differ.

Also this may help if the above doesn't work.
```
xrandr --output HDMI1 --transform 1.05,0,-35,0,1.05,-19,0,0,1
```

**Comment by Massaguana** [comment] 2016-02-09 15:03
no picture with both...

**Comment by ziggimon** [comment] 2016-02-09 15:24
You may need to find out what the output name is listed as:

```
xrandr -q
```

And adjust the `--output XXX` so represent the correct value.

**Comment by Massaguana** [comment] 2016-02-09 15:24
Strange... with the original xorg.conf with 60hz i have picture, without overscan, no jumping....
http://pastebin.com/MixZmFVj

only: i must disable "format switching" otherwise the picture jumping an little bit...

**Comment by ziggimon** [comment] 2016-02-09 15:27
Great.

The perfect xorg config for various devices may vary which is also why OpenELEC provide the option to drop in a custom version. As this now seems to have fixed your issue I'm closing it.

**Closed by ziggimon** 2016-02-09 15:27 UTC

**Comment by Massaguana** [comment] 2016-02-09 15:30
okay, Thanks for your help. But why the picture are jumping when i allow format switching? should not be allowed to avoid stuttering?

**Comment by Massaguana** [comment] 2016-02-13 12:20
Okay, 1 week testing is done... 60Hz works but there are other problems with it... There are some viewing issues i know from OEPHT white blocks/ decoding error´s ... With OEPHT i know what i must do. 50Hz and some other Settings. With PMP these Settings are not possible...
![img_1699](https://cloud.githubusercontent.com/assets/15521791/13027576/89c89e1a-d254-11e5-998b-3ffcf24d4327.JPG)
![img_1700](https://cloud.githubusercontent.com/assets/15521791/13027573/89bf77e0-d254-11e5-947a-cb4a81c1d1b4.JPG)
![img_1701](https://cloud.githubusercontent.com/assets/15521791/13027574/89c1176c-d254-11e5-80d5-919f30daf12f.JPG)
![img_1702](https://cloud.githubusercontent.com/assets/15521791/13027575/89c161b8-d254-11e5-9afb-ad316b2aa679.JPG)

**Comment by Massaguana** [comment] 2016-02-13 12:22
https://www.youtube.com/watch?v=KFFzGYy6s-U

**Comment by Massaguana** [comment] 2016-02-13 13:51
Interesting... when i change Modul part of "xcorg.conf"  from:
Modes     "1920x1080@59.94p" "1920x1080@24p" "1920x1080@60p"
to
Modes     "1920x1080@24" "1920x1080@59.94p" "1920x1080@60p"
the ChromeBox/ TV starts with 24p Screen... the picture is jumping
no it´s:
Modes     "1920x1080@50p" "1920x1080@24p" "1920x1080@59.94p" "1920x1080@60p"
and the Box Starts with 50Hz

looks like that the Box only use the first entry, is this Normal?
