### ISSUE TITLE
Investigate reports of playback not starting with 1.1 but works with 1.0.6

### ISSUE THREAD

**Issue by tru** [plexinc/plex-media-player#320] opened 2016-04-15 11:47 UTC
https://forums.plex.tv/discussion/215607/preview-1-1-win-10-will-not-start-playback-on-first-atempt#latest

**Comment by wm4** [comment] 2016-04-20 11:52
Haven't found any causes yet, nor could I reproduce it. (It has been reported by some users, though.)

Additionally I have no idea why this suddenly started happening.

I've found some potential issues in mpv and also added more logging, so we'll see where this goes.

**Comment by wm4** [comment] 2016-04-28 10:04
Fixed with `PlayerComponent: avoid that host and web go out of sync`. Essentially, playback accidentally started paused in some cases (due to the "enter" key being repeated from the preplay screen), and it wasn't possible to leave pause mode, except by seeking.

**Closed by wm4** 2016-04-28 10:04 UTC
