### ISSUE TITLE
Error playing Chernobyl TV Show

### ISSUE THREAD

**Issue by AViorel** [plexinc/plex-media-player#862] opened 2019-05-26 20:49 UTC
### Test environment

**PMS Version:** 1.15.2.793 for NAS
**PMP Version:** 3.100.1
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Windows

### Steps to reproduce
1. When i try to play Episode 1 from Chernobyl TV Show

### Current behavior
1. If i open the Episiode 1 from Chernobyl TV Show it gives me this error: "There was an unexpected error during playback. Please visit our forums if you continue to experience problems."

2. If i try to browse in the Season 1 of the Chernobyl TV Show it gives me this error: "There was an unexpected error Please visit our forums if you continue to experience problems"

3. The name of the episode is : as file: "Chernobyl S01E01 - 1-23-45.mkv", as info in PMP: "1:23:45"

4. If i try to enter in the show and play the episode 1, from Plex Web Client, it works.

5. I deleted the Episode 1 form The TV Show an now i can enter on the season directory and i can play the rest of the show.

6. Added the episode and renamed manually in Plex Web Client from "1:23:45" to "1-23-45" and now i can browse the tv show and i can play it normaly. 

### Expected behavior
1. Play the TV Show normaly

Additional notes :
PMP can't play episodes that have in the name the ":" symbol.

**Comment by mseeley** [comment] 2019-05-27 22:00
Hi @AViorel. PMP logs would be really helpful.

Do other Plex players also have trouble playing the video when it contains colons?

**Comment by dan-the-man-nz** [comment] 2019-05-28 01:16
that episode plays fine for me in PMP/Windows - have watched it didnt have any issues

checked it again on another PMP install, no issues on that either

can see the : in the screenshot below

![image](https://user-images.githubusercontent.com/906806/58444086-8591d200-814a-11e9-80a4-3581c41cbe1e.png)

**Comment by mseeley** [comment] 2019-06-11 21:23
I'll take a look at this. I think the `-` and `:` may be red herrings, this could be #865 in disguise.

**Comment by AViorel** [comment] 2019-06-11 21:34
> 
> 
> Hi @AViorel. PMP logs would be really helpful.
> 
> Do other Plex players also have trouble playing the video when it contains colons?

 Hi @mseeley. Other players don't have trouble playing the file.

I'v added a new show and strage thing happend:

 If i tryed to play the new show from "Home -> Recently Added TV" it gave me the same error.
But if i navigated to the "TV Shows" menu, selected and opened the new added show, it worked. 

I guess that the problem is at "Recently Added TV" menu.

**Comment by mseeley** [comment] 2019-06-11 22:26
Hi @AViorel that's great to hear. There's definitely a problem that seem to only pop up in the Recently Added TV list. There's nothing special about that list but definitely something is unique.

I'm going to close this out as a duplicate of #865. Please subscribe there for updates.

Thanks!

**Closed by mseeley** 2019-06-11 22:26 UTC

**Comment by tobeychris** [comment] 2019-06-18 02:28
I can confirm that I have this issue as well, and it only occurs when trying to play from Recently Added TV.
