### ISSUE TITLE
Full screen not properly displayed on ultrawide display on OS X

### ISSUE THREAD

**Issue by skadauke** [plexinc/plex-media-player#271] opened 2016-03-20 19:55 UTC
Platform: OS X 10.11.3 on rMBP Mid-2012
Plex Media Player Version: 1.0.6.229-1ce41570-macosx-x86_64
Display: Dell U3415W (3440x1440) connected via mini-DP

Welcome screen and menus are left aligned instead of centered:

![screenshot 2016-03-20 15 42 08](https://cloud.githubusercontent.com/assets/10904538/13906666/9cd9ed7c-eeb2-11e5-9fce-ec83ccdad2b3.png)

![screenshot 2016-03-20 15 41 17](https://cloud.githubusercontent.com/assets/10904538/13906681/e69647f8-eeb2-11e5-827a-769df63b9080.png)

Video playback seems to fill the available width of the screen but on-screen display elements are left-aligned and abruptly break off:

![screenshot 2016-03-20 15 41 37](https://cloud.githubusercontent.com/assets/10904538/13906689/4e1ac962-eeb3-11e5-9cd1-5d8a92926ec4.png)

Thanks!

**Comment by tru** [comment] 2016-03-20 19:56
dupe of #267

**Closed by tru** 2016-03-20 19:56 UTC

**Comment by skadauke** [comment] 2016-03-20 19:57
OK thx
