### ISSUE TITLE
CPU rate will jump to 100% at times while watching a recorded shows.  It has only been doing it a short time not sure if it started with the last update but it seams to have.

### ISSUE THREAD

**Issue by Github-63** [plexinc/plex-media-player#1026] opened 2021-05-10 23:54 UTC
Windows 10
Version 1.31.1.2262-74fdc6b7
Version 1.22.3.4392

### Steps to reproduce
1.  Have the Plex client running and watching a recorded show.  CPU much higher than before even when Plex is not recording or displaying a show.  But at times it drops back down into the 40s but what I found interesting is Plex does not show any or very little CPU and all the processing being done by QT QTwebengineprocess.
![Plex desktop, display list of recorded shows Plex server running nothing recording](https://user-images.githubusercontent.com/83985577/117737059-08d95080-b1c7-11eb-9bad-eee28c722312.JPG)
![Plex desktop not running, Plex server running nothing recording](https://user-images.githubusercontent.com/83985577/117737061-0971e700-b1c7-11eb-96e2-d9d526c86da4.JPG)
![Plex desktop, 15 minutes of show playing issues starting Plex server running and  recording](https://user-images.githubusercontent.com/83985577/117737062-0971e700-b1c7-11eb-9d28-6d5577e3bfe9.JPG)
![Plex desktop, display list of recorded shows Plex server running and  recording](https://user-images.githubusercontent.com/83985577/117737063-0971e700-b1c7-11eb-8a59-d2b2e9e744e8.JPG)
![Plex wait chain](https://user-images.githubusercontent.com/83985577/117737064-0971e700-b1c7-11eb-9b48-7e4c0ca3276d.JPG)
![Plex desktop, 45 minutes of show playing issues starting Plex server running and  recording](https://user-images.githubusercontent.com/83985577/117737065-0a0a7d80-b1c7-11eb-90b8-6520f805d9e8.JPG)
![Plex desktop, 35 minutes of show playing issues starting Plex server running and  recording](https://user-images.githubusercontent.com/83985577/117737066-0a0a7d80-b1c7-11eb-891a-797efcf03a84.JPG)
![Plex desktop started, in dashboard server recording](https://user-images.githubusercontent.com/83985577/117737067-0a0a7d80-b1c7-11eb-8fb2-eb9379b9b50e.JPG)

### Current behavior
1.  CPU high and computer is slow to respond. At times the picture will freeze up or not display but the sound starts.  When trying to pause the show it takes a long time for the show to respond to the pause or the jump forward or backward buttons or any of the controls.

### Expected behavior
1.  Able to watch a recorded show and be able to fast forward, pause, view the show or stop it when the buttons are pressed.

**Comment by Github-63** [comment] 2021-05-17 01:15
I see a new version of the server out there Version 1.22.3.4523.  Will install it tomorrow and test.  If that does not work is there a way to go back a version on the Desktop client?

**Comment by Github-63** [comment] 2021-05-19 13:13
Upgraded the server same issue.  - Is anyone looking a at these.  Can someone at least say they have seen this?

**Comment by Github-63** [comment] 2021-05-19 13:18
I have the plex for life account and I think once it the software starts working again I don't  plan to put on any patches since there has been on more that one occasions that Plex did not work well after installing the updates.  And now with the software almost unusable I don't see where anyone is even looking at issues.   If the issue is not clear or you need more information ask me I will clarify or add more to this if that will help.

**Comment by Github-63** [comment] 2021-05-19 16:56
[Plex Media Server Logs_2021-05-19_12-52-33.zip](https://github.com/plexinc/plex-media-player/files/6510512/Plex.Media.Server.Logs_2021-05-19_12-52-33.zip)

**Comment by mseeley** [comment] 2021-05-19 17:39
Hi @Github-63, please restart the app, observe the unexpectedly high CPU usage for several minutes, quit the app, then provide the most recent of each of these files:

- `%LOCALAPPDATA%\Plex\Logs\Plex.log`
- `%LOCALAPPDATA%\Plex\Plex Media Server\Logs\Plex Media Server.log`

> Able to watch a recorded show and be able to fast forward, pause, view the show or stop it when the buttons are pressed.

Are you referring to shows recorded from a Plex DVR? If so, is it _only_ DVR recorded content that is causing problems?

**Comment by Github-63** [comment] 2021-05-20 01:36
[Plex.log](https://github.com/plexinc/plex-media-player/files/6512302/Plex.log)
[Plex Media Server.log](https://github.com/plexinc/plex-media-player/files/6512303/Plex.Media.Server.log)

**Comment by Github-63** [comment] 2021-05-20 01:52
99% of what we watch is what is recorded from the DVR.  I have not tested the other.  it does seem like the longer the app stay up the worse it gets.  Not as much by CPU% but in time to respond.  we had been watching the National parks show from PBS as one of the last things during this log.  After stopping the show I tried to start it up again and it took a long time for it to finally start playing.  I leave task manager up and when switch to it  it will show 100% cpu then drop back down to 40-60%.  If i shutdown the Plex client the cpu will drop to about 3% even with the Plex server running.  Starting the plex client up it jumps up to about 40% even when nothing is playing.  That is what i was trying to show with the pictures on the first post.  Plex server running nothing recording CPU 3%.  The pictures were named with a description of what was happening but it appears that the names don't show up but they had names like "Plex desktop not running, Plex server running nothing recording.JPG"  and "Plex desktop, display list of recorded shows Plex server running nothing recording.JPG"

**Comment by Github-63** [comment] 2021-05-20 03:14
[Plex Media Server.log](https://github.com/plexinc/plex-media-player/files/6512608/Plex.Media.Server.log)
[Plex.log](https://github.com/plexinc/plex-media-player/files/6512609/Plex.log)

**Comment by Github-63** [comment] 2021-05-20 03:17
The issue was already occurring about 10:50 pm when i tried to skip 30sec forward it started just freezing up.  Even the spinning circle was not spinning.

**Comment by Github-63** [comment] 2021-05-20 13:46
I

**Comment by mseeley** [comment] 2021-05-22 01:20
Hi Github-63. I've carefully reviewed the logs you provided. I've also watched several hours of recorded and live DVR content. 

I've been unable to reproduce massive CPU, GPU, or memory usage. I see the user interface performance less smooth during playback though I haven't witnessed it breaking down as you have.

With nothing playing our a CPU is around 4% for me. GPU can still 50-60% if the `Activity` icon in the app's header is animating. We're aware of the high cost animation has on the UI and have intentions to optimize.

If you're using this as a living room TV substitute please try our HTPC app: https://forums.plex.tv/t/introducing-plex-htpc/703075. It shares much code with the app you're testing here, it may have the same issue. Although perhaps the UI reduces overhead.

That's the best feedback I can provide on the situation you're facing.

**Comment by kanetse** [comment] 2021-05-31 20:31
I have seen this problem as well, but for me, it is not limited to Plex-DVR recordings.  I see it appear on everything, sometimes even if I just leave Plex running in the background.  I can tell because the UI becomes very sluggish at that point (whether in playback or even menus after playback is stopped), and like @Github-63 , Windows task manager will show that QT QTwebengineprocess is consuming a high amount of CPU.  

It only started occurring under the most recent release of the Plex Media Player, 1.31.1.2262-74fdc6b7.  Closing the program and reopening it fixes the problem.  It doesn't happen every time, but I run Plex enough that I encounter it daily.

The next time it happens, I will generate some logs following @mseeley's instructions and attach them here.

**Comment by Github-63** [comment] 2021-06-01 16:28
restarting plex client does help but it does not take long before it is sluggish and not responding.  Is there a way i can get a copy of the previous version.  Currently i am running Plex-1.31.1.2262-74fdc6b7 and i did not have this issue before installing it.

**Comment by Github-63** [comment] 2021-06-01 16:29
HTPC app did not work so well either.  I could back up but not forward any of the recordings i tried with it.

**Comment by Github-63** [comment] 2021-06-08 22:42
It appears that the problem has been solved.  I have been using "Plex for windows"  that just shows the name plex when running.  I installed Plex media player Windows 7 SP1 or later (64-bit only). 2.58.0.1076-38e019d and it worked just fine.  When i tested Plex  for windows it now works fine too.  So   one of the common  files use between the 2 appear to be the issue.  Later on to I may uninstall PMP and see if PFW still works.  IF it does i will uninstall it and reinstall it and see if the issue comes back which I would assume it would.

**Comment by Github-63** [comment] 2021-06-09 23:16
When I just had the Plex for windows installed I was having problems.. Now I have both Plex for windows and Plex media player. The problems went away after installing plex media player. I still have PMP installed and have been using both off and on but Plex for Windows more and have not had any trouble since.

**Comment by mseeley** [comment] 2021-06-09 23:28
Hi @Github-63. Going to close this out as it sounds like the apps are working better for you.

**Closed by mseeley** 2021-06-09 23:28 UTC
