### ISSUE TITLE
Major flickering on 1024x768

### ISSUE THREAD

**Issue by hcw-rohan** [plexinc/plex-media-player#128] opened 2015-11-04 01:19 UTC
I use a projector for my HT and its native res is 1024x768. When loading Plex in this res It has major flickering making it unusable.

OS: Win 10
PMP: 1.0.1.42

**Comment by tru** [comment] 2015-11-04 06:18
Dupe of https://github.com/plexinc/plex-media-player/issues/89

TL;DR we might do something to ease the pain but for now PMP is 16:9 only.

**Closed by tru** 2015-11-04 06:18 UTC
