### ISSUE TITLE
RPi2: Movies stretched to 16:9 since 1.0.3

### ISSUE THREAD

**Issue by billiloumez** [plexinc/plex-media-player#191] opened 2016-01-04 12:40 UTC
Since 1.0.3 all my movies strech to 16:9 and lose their correct aspect ratio on my RPi2.

http://forums.plex.tv/discussion/199842/rpi2-hdmi-poweron-true-causing-vertical-stretch#latest
http://forums.plex.tv/discussion/201053/aspect-ratio-locked-at-16-9#latest

Logfile is attached.

[plexmediaplayer.zip](https://github.com/plexinc/plex-media-player/files/77185/plexmediaplayer.zip)

**Comment by wm4** [comment] 2016-01-05 10:10
I've tried to reproduce the problem (yesterday with my dev version, right now I tried 1.0.3), and it seems it works for me.

Are you sure you're not forcing the aspect ratio in a custom mpv.conf or so?

Can I see a screenshot of it? Preferably with debug overlay enabled.

**Comment by billiloumez** [comment] 2016-01-05 10:25
I've tried several movies and all are stretched to 16:9, I don't use a custom mpv.conf, I just double checked, there is no mpv.conf in my \\plexmediaplayer\Configfiles folder.
I have attached a foto where you can see the effect pretty well, because the earth is not round, but oval:
![20160105_112159](https://cloud.githubusercontent.com/assets/16539587/12112752/dbf6dcf8-b39e-11e5-805d-398b3a5350bd.jpg)

**Comment by wm4** [comment] 2016-01-05 12:31
Ah, I see this uses transcoding. Can you post a log from when playing exactly this video? Also, can you try again with transcoding disabled?

**Comment by billiloumez** [comment] 2016-01-05 12:38
Oh yeah, sorry, I forgot that I've switched off direct play, but just for the reason to try, if the same problem occurs when transcoding. It always stretches, no matter if I use direct play or transcoding.
Here is the logfile:
[plexmediaplayer.zip](https://github.com/plexinc/plex-media-player/files/78391/plexmediaplayer.zip)

**Comment by wm4** [comment] 2016-01-05 12:53
Never mind, transcoding can't be blamed.

**Comment by wm4** [comment] 2016-01-05 13:21
Will be fixed in the next build.

**Closed by wm4** 2016-01-05 13:21 UTC
