### ISSUE TITLE
[RP2] Wrong media profile for HEVC/H265 when enabling direct play

### ISSUE THREAD

**Issue by Clock** [plexinc/plex-media-player#112] opened 2015-10-31 15:15 UTC
Deepseth: "The player supports HEVC, and you have direct play enabled, so it's sending your player HEVC video to decode locally, rather than transcoding it. Unfortunately, as the RPi2 has no HW decoding support for HEVC, so it's punting it to the CPU to decode in software. As the CPU is still relatively puny, it's struggling, resulting in choppy playback.

This wasn't happening with Rasplex because PHT didn't have HEVC decoder support, so it never sent it HEVC video.

Maybe try disabling direct play and direct stream and playing again, it might force it to transcode, hopefully to h264, which your RPi2 will be able to fire in the HW decoder.

If all of the above is true, then this qualifies as a bug of sorts for the RPi2 embedded image, and PMP on RPi2 shouldn't report HEVC support back to PMS, which then would automatically force transcoding of any HEVC/H265 content back to H264.

Unless someone can point out where I've gone wrong with the above, I'd recommend filing a new bug on Github for this to be noted and fixed for a future release, as more and more people will be impacted by this in future. It's similar to the one you linked (PMP on RPi2 reporting support for media type that RPi2 hardware doesn't support), but a different media type (HEVC video rather than 10bit colour video)"

More info: https://forums.plex.tv/discussion/189633/pmp-on-raspberry-pi-2-do-i-need-the-decoder-licenses

**Comment by wm4** [comment] 2015-10-31 15:20
Very likely a duplicate of #109, but not certain yet.

**Comment by mseeley** [comment] 2016-01-05 00:14
Currently PMP's profile is wildly permissive and allows all codecs for every container. We have three options
1. Define every video codec for every container and omit HEVC for any container on the RPI2.
2. Augment the profile's container+codec whitelist with a blacklist which strips HEVC support on the RPI2.
3. Detect when the MDE returns an HEVC `Part` then disable DP and take a second trip through the MDE.

Option 1: fits precisely within our infrastructure although could be challenging to find all combinations.
Option 2: has the least change in the profile level although the MDE would need to learn new tricks.
Option 3: code smell.

@wm4 is there a canonical source for supported container+codec combinations?

**Comment by wm4** [comment] 2016-01-05 14:08
>@wm4 is there a canonical source for supported container+codec combinations? 

This is hard. On the desktop platforms, essentially anything FFmpeg supports is supported. It's the same on RPI2, except even though HEVC "works", it's too slow to be useful. It's best to define video codec support on RPI as a whitelist. Actually, the only video codec that works by default is h264 (roughly following the Bluray limits, so no 4K or 10 bit). The container and audio codec support remain the same.

To make this even worse, a RPI owner can purchase VC-1 and MPEG-2 licenses. When PMP starts, we need to check whether licenses for these codecs are present, and if so, allow them in the profile.

Not sure how this actually affects the profile code. Although it probably won't be pretty.

**Comment by mseeley** [comment] 2016-02-09 07:19
> Actually, the only video codec that works by default is h264 (roughly following the Bluray limits, so no 4K or 10 bit)

@firasdib has whitelisted h264 by default for all video containers supported by the RPI2. Then at run time  VC-1 and MPEG-2 support is added. I think this issue can close out with https://github.com/plexinc/plex-web-client/pull/4136/.

**Comment by firasdib** [comment] 2016-02-15 14:43
This should be solved with the new player profile, but I can't test it atm. Can anyone give it a go?

**Comment by firasdib** [comment] 2016-03-04 08:14
Where are we with this issue now? RPi2 will transcode h265 videos, but how about RPi3? Do we need a separate player profile there, or does it not support h265 either?

**Comment by tru** [comment] 2016-03-04 08:39
Afaik it doesn't support h265 so we could continue to use the same profile.

**Comment by firasdib** [comment] 2016-03-04 09:55
Ok. Closing this issue for now, reopen if you feel that this needs to be revisited.

**Closed by firasdib** 2016-03-04 09:55 UTC
Labels: component:web, priority:high
